### ISSUE TITLE
Testing prorate on subscription

### ISSUE THREAD

**Issue by rained23** [braintree/braintree_php#102]
Hi,

I wanted to test manual prorate when user upgrading/downgrading a plan.

I want to test to make sure the output is the same as I wanted, I am using discount to do this
by cancelling current subscription and create new subscription and add a discount.

How can I test this without waiting a month to get the output ?

Because I want to make sure that the remaining discount will be carried forward to the next billing.

Below is the sample code that I will use to create a new subscription with a discount based on prorated amount.

```
Braintree_Subscription::create(
  'paymentMethodToken' => $token,
  'planId' => $planId,
  'discounts' => [
    'add' =>[
        'inheritedFromId' => 'prorate',
        'numberOfBillingCycles' => 1,
        'amount' => 20
    ]
]
);
```
The plan price is USD 10.

I just want to make sure that the first and second billing will be 0 because Braintree support told me
that the discount will be carried forward, but I am unable to test this because I need to wait 1 month to able to get the output.

**Comment by ryanjpodonnell** [comment]
We do not have any way for merchants to test this without waiting for their subscription to charge.

 On a side note, it seems like you can make an [update](https://developers.braintreepayments.com/reference/request/subscription/update/php) which would accomplish the same thing as canceling and creating a new subscription.

The way your subscription should behave is as you are expecting. On the first billing date, the discount would be applied. The customer would not get charged for this transaction and a $10.00 credit would be applied to the subscription. On the next billing date, the credit would cancel out the subscription charge and there would be no transaction here as well.

I think these ideas will address the concerns as I understand them, but I would reach back out to support if you have any more specific questions on modifications. For now, I am going to close this issue.
