### ISSUE TITLE
Webhook documentation broken

### ISSUE THREAD

**Issue by Paratron** [braintree/braintree_php#103]
This seems to be a general bug/mistake of the braintree webhooks - I wonder why this didn't occur to somebody, much earlier.

In the [webhook documentation](https://developers.braintreepayments.com/guides/webhooks/parse/php) its written that webhooks will be called through a POST request and the `bt_payload` and `bt_signature` is transferred inside the POST-body.

The URL is called with the POST method, but the two parameters are transferred as GET parameters - I have no idea why this is the case.

I uploaded a dump of a webhook test request so you can see it for yourself: http://wearekiss.com/files/capture.html

**Comment by Paratron** [comment]
Update: It seems like this only applies to the test call of the webhook. I now sent a payment processed webhook and its transmitted in the POST body.

**Comment by ryanjpodonnell** [comment]
@Paratron, good catch! It looks like we need to update some snippets in our documentation. Just to clarify, we send webhooks as post requests. However, the arguments `bt_payload` and `bt_signature` are sent via URL parameters. This means that you would need to use [$_GET](http://php.net/manual/en/reserved.variables.get.php) to access these variables.

**Comment by ryanjpodonnell** [comment]
@Paratron You should now be able to access the parameters via the `$_POST` method. I'm going to close this, but let us know if there are any issues.
