### ISSUE TITLE
Errors at specific levels always return null

### ISSUE THREAD

**Issue by m-amr** [braintree/braintree_php#105]
Based on Documentation 
https://developers.braintreepayments.com/reference/general/validation-errors/overview/php
I am trying to handle  Braintree_Customer::create()  response error
and Errors at specific levels always return null 

    foreach($result->errors->deepAll() AS $error) {
        echo($error->code . ": " . $error->message . "\n");
        }

Doesn't echo anything  and count($result->errors->deepAll() ) is 0

and errors at specific levels always return null 

    foreach($result->errors->forKey('customer')->shallowAll() AS $error) {
        print_r($error->attribute . ": " . $error->code . " " . $error->message . "\n");
    }

    foreach($result->errors->forKey('customer')->forKey('creditCard')->shallowAll() AS $error) {
         print_r($error->attribute . ": " . $error->code . " " . $error->message . "\n");
    }

    foreach($result->errors->forKey('customer')->forKey('creditCard')->forKey('billingAddress')->shallowAll() AS $error) {
        print_r($error->attribute . ": " . $error->code . " " . $error->message . "\n");
     }

The only why to handle errors is checking the response object

    public function getCustomerCreationError(\Braintree_Result_Error $result){
        /** @var \Braintree_Result_CreditCardVerification $creditCardVerification */
        $creditCardVerification = $result ->creditCardVerification;
        $status = $creditCardVerification->status;

        switch($status){
            case 'processor_declined':
                 // handle processor_declined
                break;

            case 'gateway_rejected':
                if($creditCardVerification->gatewayRejectionReason === 'cvv'){
                    // handle cvv
                }
                break
                ;
            case 'failed':
                // handle failed;
                break;
        }
        }

I think there something wrong in documentation is there is a right way to check for response errors ?

**Comment by ryanjpodonnell** [comment]
@m-amr I believe there is a little confusion surrounding verification results here. The credit card verification result here is not an error (it is simply the result of the verification). If you made a bad call when creating a customer create, you would get an error result object back. I am going to close this issue. If you have any other questions, feel free to reach out to our support team (support@braintreepayments.com).
