### ISSUE TITLE
Broken compatibility since 3.6

### ISSUE THREAD

**Issue by AliHichem** [braintree/braintree_php#107]
I'm wondering why would you guys go for completely new class names when moving from v3.5 to v3.6 ? Renaming the core classes to follow whatever it is (psr-0 to psr-4 probably)  should happen for major versions (v3 to v4 for instance ) and not between intermediate version ..

**Comment by eusonlito** [comment]
Check issues https://github.com/braintree/braintree_php/issues/94 and https://github.com/braintree/braintree_php/issues/106

If you want to have a controlled version, you should use `"braintree/braintree_php" : "3.5.*"` in your `composer.json`.

**Comment by matthewpatterson** [comment]
Hey @AliHichem,

I'm a developer here at Braintree. Actually, all of the old class names are still available for use. We aliased all of the old class names to the new classes; for example:

```php
<?php
namespace Braintree;

final class Transaction extends Base
{
}
class_alias('Braintree\Transaction', 'Braintree_Transaction');
```
(from https://github.com/braintree/braintree_php/blob/3.6.1/lib/Braintree/Transaction.php#L543)

These aliases will be removed in the next major version of the library.

There are some error messages which include a class name that would have changed in v3.6.0, but everything else should work just as it did before.

If you are having trouble using the old classes, please email support@braintreepayments.com. They'll be able to look into your specific issue and find a resolution.

-matt

**Comment by AliHichem** [comment]
@matthewpatterson thank you for your helpful answer, I'm indeed having trouble with the v3.6.0 where those aliases doesn't seem to work for me. For now I'm ok with the v3.5.0 and I'll wait for the v4 before migrating my code, I emailed you guys because renaming classes from psr-0 to psr-4 shouldn't happen in an intermediate version IMO. 

@eusonlito that's not what I'm asking and your comment about composer is pretty obvious and kind of out of subject. Thank you for commenting anyway.

Thank you guys for your answers,  keep on the good work and have a nice weekend !

**Comment by matthewpatterson** [comment]
@AliHichem I would still recommend emailing support@braintreepayments.com with some details of your set up. The class aliases worked for us in all of our backwards-compatibility tests, but if something is not working for you, then it is likely that it's not working for others as well.

**Comment by eusonlito** [comment]
@AliHichem sorry my comment :)
