### ISSUE TITLE
v3.6.0 breaks backward compatibility

### ISSUE THREAD

**Issue by maidmaid** [braintree/braintree_php#108]
``v3.6.0`` changes its autoloading and breaks backward compatibility. You should increment major number by creating ``v4.0.0``.

**Comment by crookedneighbor** [comment]
@maidmaid All the old class names are aliased to the new classnames. See [this comment on this issue for more info](https://github.com/braintree/braintree_php/issues/107#issuecomment-152577536).

Some PHP frameworks (like Symfony) had trouble with the aliases, so we released a patch with a fallback for for PSR-0 with the [3.6.1 release](https://github.com/braintree/braintree_php/releases/tag/3.6.1).

Going to close this now, but if upgrading to 3.6.1 does not solve your issue, please open a ticket [on our support site](https://support.braintreepayments.com/) with the details of your integration so we can figure out what's causing the problem and release a patch to fix it. If you're having issues, I'm sure others are having issues as well.
