### ISSUE TITLE
WebhookNotification missing constant

### ISSUE THREAD

**Issue by therool** [braintree/braintree_php#109]
The documentation mentions that there is a constant **Braintree_WebhookNotification::CHECK** but it is missing in v3.6.1.

https://developers.braintreepayments.com/guides/webhooks/testing-go-live/php#test
https://developers.braintreepayments.com/reference/general/webhooks/test/php#notification-types

**Comment by omgrr** [comment]
@therool The documentation for `Braintree_WebhookNotification::CHECK` went out before the constant was added to the library. A new version of the library should be released soon. In the meantime, I'll leave the issue open and we will report back once it is out. 

Thank you! 
Jerry

**Comment by crookedneighbor** [comment]
Thanks for bringing this to our attention @therool, [the constant](https://github.com/braintree/braintree_php/blob/36c2b9de6793a28e25f5f9e265f60aaffef2cfe2/lib/Braintree/WebhookNotification.php#L24) is now available in v3.7.0.
