### ISSUE TITLE
Update developer documentation to reflect new namespaces

### ISSUE THREAD

**Issue by andrewnicols** [braintree/braintree_php#112]
I've been using your new namespaces for a new project (in Symfony), however, all of your documentation (e.g. https://developers.braintreepayments.com/reference/request/transaction/search/php#created_at) says to use the old namespace.

Would be really handy if you could correct that ;)

**Comment by wjr1985** [comment]
@andrewnicols thanks for mentioning this! We're currently working on updating the documentation and should have it rolled out soon.

**Comment by githoober** [comment]
@wjr1985 is there a ticket or anything of that kind to follow a progress of updating the docs?
