### ISSUE TITLE
PaymentMethod don't have factory method

### ISSUE THREAD

**Issue by danielmir** [braintree/braintree_php#115]
I don't know if it is an issue, but I think PaymentMethod should have factory method as other classes do, I have a problem working with it on symfony framework, using cometcult/braintree bundle.

**Comment by raymondberg** [comment]
Hi, @danielmir. I'm interpreting your question to be two different things.

1 - You are wondering why there is no PaymentMethod->factory method. 
2 - You have a problem using the PHP client library with Symfony

For 1, we will review to see if this would be a valuable refactor. But for 2, Github is not a great forum for discussing individual problems with an integration. I would encourage you to [contact Braintree support](https://support.braintreepayments.com) to provide more specifics about your environment and the problem you are experiencing. 

I'm going to close this issue for now, but feel free to reopen if you have a specific connection between the lack of a factory method and the issue that you're seeing.
