### ISSUE TITLE
Braintree sub-merchant-account webhook

### ISSUE THREAD

**Issue by shreeya-detroja** [braintree/braintree_php#117]
I m trying to validate sub-merchant-account that it is valid or not which is entered by third party,
So for that I created webhook for sub-merchant-account on control-panel,
From that I can also fetch the value of bt_signature and bt_upload,
i applied that value to below code.
        $sampleNotification = Braintree_WebhookTesting::sampleNotification(
                        Braintree_WebhookNotification::SUBSCRIPTION_WENT_PAST_DUE, 'my_id'
        );
        $notification = Braintree_WebhookNotification::parse(
                        $sampleNotification['bt_signature'], $sampleNotification['bt_payload']
        );
But it return an error : Undefined property on Braintree_WebhookNotification: merchantAccount
So, How could i validate merchant account is exist or not?
and what would be the value of my_id?
what would be the value of api configuration? (It should be the master-merchant-account api?)
I m using cakephp.

Please help, need to be finished today.
Thanks in advance.

**Comment by omgrr** [comment]
Hello @shreeya-detroja, In order for me to try and reproduce the error you are receiving, would you be able to provide what version of PHP your using and what version of the library?

`my_id` represents the id of the object that is returned and [depends on the type of webhook](https://developers.braintreepayments.com/reference/general/webhooks/overview#notification-types). For example, the id in the case of a subscription webhook would be the id of the subscription. The id in the case of a sub merchant account webhook would be the id of a sub merchant account. 

Also in the future if you ever need a more immediate response, I recommend contacting [support](https://support.braintreepayments.com).

**Comment by omgrr** [comment]
I'm going to close this for now, if this issue comes up again feel free to reopen.
