### ISSUE TITLE
Braintree_Customer::find and Braintree_Subscription::find return wrong type

### ISSUE THREAD

**Issue by ir-fuel** [braintree/braintree_php#118]
There seems to be a bug in `Braintree_Customer::find` and `Braintree_Subscription::find`

according to the docs at:

https://developers.braintreepayments.com/reference/response/customer/php

a call should result in a `result object` containing a customer, but instead it directly returns a customer object.

Same for the subscription find.

**Comment by jdlc** [comment]
Hi @ir-fuel, thanks for your comment. As stated [here](https://developers.braintreepayments.com/reference/general/result-objects/php), API calls without validations, such as #find, will return an array of customer objects. We will look into updating our documentation to make this more clear.
