### ISSUE TITLE
Transaction response should contain data about the refunded amount

### ISSUE THREAD

**Issue by m-amr** [braintree/braintree_php#119]
I have faced some cases when customer paid on multiple gateways
lets say example
1- Customer paid $100 as TransactionA t
2- Then customer pay $100 as TransactionB
3- I have refunded $50 from TransactionA
4- Then for some reason i have to refund $150 there is no data in TransactionA tell me that i have refunded $50 or i can refund from it only $50.

I have implement stripe before (they called the Transaction a Charge)
and in Charge Object there is a field called $charge->amount_refunded 
so i know exactly how much amount was refunded or i can refund from this charge

I think that on partial refunds Transaction object should contain data about the refunded amount.

Thanks.

**Comment by crookedneighbor** [comment]
The transaction response object [has a `refundIds` array](https://developers.braintreepayments.com/reference/response/transaction/php#refund_ids). You can use these transaction ids to look up the refund amounts to calculate how much you can refund.

There are no immediate plans to add the refunded amount directly to the transaction object.
