### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by 719media** [braintree/braintree_php#120]
Hi guys

Support said I should leave a feature request on github, so I am.
I am looking for a way to "get all transactions that experienced activity in range".

Right now, I can run a query using

```
\Braintree_Transaction::search([
    \Braintree_TransactionSearch::createdAt()->between($start_datetime, $end_datetime)
]);
```

or

```
\Braintree_Transaction::search([
    \Braintree_TransactionSearch::disputeDate()->between($start_datetime, $end_datetime)
]);
```

but, unfortunately, there is no way to do this query for updatedAt. This would be useful because you could use it to catch up on any activity that happened to a transaction, even if that activity was, say, a dispute that happened today on a transaction that otherwise did not have any activity in the last 4 months. I would love to be able to:

```
### below is not valid
\Braintree_Transaction::search([
    \Braintree_TransactionSearch::updatedAt()->between($start_datetime, $end_datetime)
]);
```

Thank you for your time and consideration.

**Comment by crookedneighbor** [comment]
Thanks for the suggestion @719media. This would require changes to the Braintree Gateway as well as changes to the server-side sdks. Currently there are no plans to implement this feature, but we'll keep it in mind as we move forward. 

Regarding tracking disputes, you may want to look into [dispute webhooks](https://developers.braintreepayments.com/reference/general/webhooks/dispute/php), as it would give you immediate information on the status of a dispute.

**Comment by jesper-sjovall** [comment]
Hi.

This is a feature that we also want to use when we fetch subscription information.

```
\Braintree\Subscription::search([
    \Braintree\SubscriptionSearch::planId()->is($plan_id),
    (new \Braintree\RangeNode('updatedAt'))->between($from, $to),
]);
```

Instead for only fetching the time range we is interesting in we is now force to fetch all subscription and doing the filtering on our side every day.

Which means unnecessary load on both side if we have thousand or more subscribes and only some of them has be update the last 24 hours.

We have already look into [webhooks](https://developers.braintreepayments.com/reference/general/webhooks/dispute/php) but in our current design this will be very hard to implement.
