### ISSUE TITLE
Some gateways are marked as final, some aren't

### ISSUE THREAD

**Issue by githoober** [braintree/braintree_php#121]
We are trying to write a unit test that accepts \Braintree\TransactionGateway instance as a constructor parameter. For this parameter we hoped to create a mock to not hit any Braintree services while tests are run, but unfortunately the class \Braintree\TransactionGateway is marked as final and there is no (simple) way to work around this.

My question is, what defines whether a gateway in Braintree folder is marked as final? I checked and found that only MerchantAccountGateway, MerchantGateway, TestingGateway, TransactionGateway are marked as final classes out of all 20 gateways.

**Comment by matthewpatterson** [comment]
Hey @githoober,

We have actually moved away from using final classes in this library, but have not had an opportunity to remove the `final` attribute of any existing classes. We are certainly open to a pull request to accomplish this change to make testing easier!

-matt
