### ISSUE TITLE
Can you expand WebhookTesting.php for _subscriptionChargedSuccessfullySampleXml, please?

### ISSUE THREAD

**Issue by FallDi** [braintree/braintree_php#123]
If it possible please add subscription billingPeriodStartDate & billingPeriodEndDate. Tnx!

**Comment by pblesi** [comment]
@FallDi I added `billing-period-start-date` and `billing-period-end-date` to the `subscriptionChargedSuccessfullySampleXml` and it will be available in our next release.

**Comment by FallDi** [comment]
Thank you!

**Comment by FallDi** [comment]
If it possible please add also **nextBillingDate** and **price** for test xml data an. 
And **processorResponseText** with **processorResponseCode** for transaction.
Tnx!
