### ISSUE TITLE
Braintree_Exception_Authorization error when setting coinbase account as default payment method

### ISSUE THREAD

**Issue by hootener** [braintree/braintree_php#125]
I'm in the CoinBase beta for braintree. Integration seems to be working fine except for when I attempt to make a coinbase payment method the default payment method for a user. Specifically, the PHP library throws a ```Braintree_Exception_Authorization``` error immediately after the following call

    $result = \Braintree_PaymentMethod::update($method->token,
            [ 'options' => [
                'makeDefault' => true
              ]
            ]
          );

where method is an object of the type ```Braintree_CoinbaseAccount```  obtained from calling ```$customer->paymentMethods()```. Specifically, the object is included in an array of other payment methods for the customer (one credit card and one paypal account). From the paymentMethods array, the coinbase info looks as follows:

    Braintree_CoinbaseAccount::__set_state(array(
     '_attributes' => 
    array (
      'token' => 'user-token',
      'userId' => 'user-id',
      'userName' => 'Satoshi Nakamoto',
      'userEmail' => 'satoshi@example.com',
      'imageUrl' => 'https://assets.braintreegateway.com/payment_method_logo/coinbase.png?environment=sandbox',
      'createdAt' => 
      DateTime::__set_state(array(
         'date' => '2016-03-16 22:39:53.000000',
         'timezone_type' => 3,
         'timezone' => 'UTC',
      )),
      'updatedAt' => 
      DateTime::__set_state(array(
         'date' => '2016-03-17 16:23:53.000000',
         'timezone_type' => 3,
         'timezone' => 'UTC',
      )),
      'default' => false,
      'subscriptions' => 
      array (
      ),
      'customerId' => '24098327',
    ),
    )),

Setting other payment methods to default (e.g., credit card, paypal) appears to work. But it does not seem to be the case when using CoinBase. Any guidance would be appreciated. 

Thanks!

**Comment by hootener** [comment]
In case anyone else stumbles across this issue. Here's the response via email I received from braintree regarding the problem:

```... I talked with some of our Coinbase developers, and apparently this is a known issue that is slatted for update but doesn’t yet have a set completion date. I’m sorry for the inconvenience, and I will be sure to reach out as soon as we have an update, but at the moment there isn’t any way to change your stored Coinbase payment method to the default.```

To note, all other coinbase functionality seems to work fine, you just can't set it as a default payment method.

**Comment by jdlc** [comment]
@hootener,
Thanks for pointing this out and updating the issue with your response from Braintree support. Since we don't have a set date for when this will be resolved, I'm closing the issue.

**Comment by hootener** [comment]
:clap:
