### ISSUE TITLE
Documentation on website not up to date

### ISSUE THREAD

**Issue by tschoffelen** [braintree/braintree_php#126]
One of the very first steps of the website PHP tutorial talks about a class called `Braintree_Configuration`, instead of `Braintree\Configuration`, which is how the class is actually called.

https://developers.braintreepayments.com/start/hello-server/php

**Comment by jdlc** [comment]
@tschoffelen
Both PSR-0 and PSR-4 namespacing are supported in the Braintree PHP client library, so the class can be invoked with either `Braintree_Configuration` or `Braintree\Configuration`. If you have any other comments about our documentation, please click the "Give us some feedback on this page" at the bottom of any docs page. Thanks!
