### ISSUE TITLE
Does ClientToken have an expiration period?

### ISSUE THREAD

**Issue by Pavel910** [braintree/braintree_php#127]
Hey guys, I'm sorry to put this here, I just really need to know this and there is no better place to ask.

So the question is: does a generated client token (generated with `$customerId`) ever expire, or can I store it in DB for each of my customers to avoid calling Braintree API each time I get to a checkout page?

Thanks a lot and sorry again for putting this here!
Cheers

**Comment by matthewarkin** [comment]
support@braintreepayments.com will generally be a better place to ask these sorts of issues as they're not directly related to the PHP client library but rather the API itself.

I would generally say you want to generate a new clientToken on the checkout page, while the docs don't specifically give an expiration for the clientToken, they should only be used once. 

> These should not be reused; a new client token should be generated for each customer request that's sent to Braintree. For security, we will revoke client tokens if they are reused excessively within a short time period.
https://developers.braintreepayments.com/start/overview#client-token

**Comment by kexline4710** [comment]
@pavel910 - @matthewarkin is exactly right. I'm going to close this issue as it appears to be resolved.
