### ISSUE TITLE
Transaction::search return  results from wrong createdAt range

### ISSUE THREAD

**Issue by viktym** [braintree/braintree_php#139]
I'm running this:
```
// $startDate, $endDate have some value XX, YY in UTC
Braintree\Transaction::search(
    [Braintree\TransactionSearch::createdAt ()->between($startDate, $endDate)]
);
// returning items have createdAt  XX + 5h,  YY + 5h in UTC (in my case)
```

Looks like a bug

Actual: returning items have createdAt between  XX + 5h and   YY + 5h in UTC
Expected: returning items have createdAt between  XX and  YY in UTC

Library version: 3.7.0, 3.13.0

**Comment by viktym** [comment]
Resolve by adding Z identifier to date string - "2016-06-16 22:55:55Z"

**Comment by raymondberg** [comment]
I'm glad you were able to resolve. If you follow the [examples on searching with Datetime objects](https://developers.braintreepayments.com/reference/request/transaction/search/php#status-changes) you should find success. Many timestamp issues arise from the time settings of a PHP environment conflicting with expectations in the API. As such, it's a great idea to [contact Braintree Support](https://support.braintreepayments.com) if you run into any more of these issues.
