### ISSUE TITLE
Test Maestro cards unsuccessful

### ISSUE THREAD

**Issue by siva-farshore** [braintree/braintree_php#140]
Now I'm working on the sandbox environment. By checking different cards, Maestro card not giving the success result.

> card number : any test maestro card number from the web.

Code used:
<pre>
$result = Braintree_Customer::create([
    'firstName' => 'Mike',
    'lastName' => 'Jones',
    'company' => 'Jones Co.',
    'paymentMethodNonce' => $this->request->data['cc_nonce'],
    'creditCard' => [
        'cardholderName' => $this->request->data['cc_nameOnCard'],
        'number' => $this->request->data['cc_number'],
        'expirationMonth' => $this->request->data['cc_expiryMonth'],
        'expirationYear' => $this->request->data['cc_expiryYear'],
        'cvv' => $this->request->data['cc_cvv'],
    ]
]);`
</pre>

But always got the same output

> 81703: Credit card type is not accepted by this merchant account.

Please help  me resolve this issue. 

Thanks.

**Comment by matthewarkin** [comment]
Maestro is only supported in some countries, https://www.braintreepayments.com/payment-methods/accept-credit-cards, as this is not an issue with the library, you should contact support about this  https://www.braintreepayments.com/contact
