### ISSUE TITLE
Add injectable http client

### ISSUE THREAD

**Issue by githoober** [braintree/braintree_php#141]
All gateways contain this piece of code:

`$this->_http = new Http($gateway->config);`

This breaks Inversion of Control principle since this dependency should be injectable for an easy swap with a different implementation. (and I am not even talking about interfaces).

Please at least introduce a setter for Http client so it's possible to have one http client for all gateways. By having it, it would be easy to intercept any exceptions thrown in the http client methods.

**Comment by matthewpatterson** [comment]
Hi @githoober,

Thank you for your suggestion.

One of the most important things I think about as I write software is making it easy for other developers to do the right thing. I think this is visible in how we've engineered our server-side client libraries: they are very much self-contained with minimal external dependencies and very little required setup.

Unlike other languages, PHP does not have a common interface for HTTP clients. This means there's no good way for us to set expectations about what methods will be called on the client, and so it becomes very easy to do the wrong thing by mistake. A perfectly reasonable person might expect that they could inject a Guzzle client, or some other client, when in fact there is no guarantee that it'd work at all.

I don't believe we can implement your suggestion at this time. If there is anything in particular about our `Http` implementation that your are having trouble with, I would recommend reaching out to our [support team](https://articles.braintreepayments.com).

Thanks,

-matt

**Comment by AidasK** [comment]
As of 2022 this is no longer true and all modern libraries are now migrating to PSR:

https://www.php-fig.org/psr/psr-7/
https://www.php-fig.org/psr/psr-15/
https://www.php-fig.org/psr/psr-17/
 https://www.php-fig.org/psr/psr-18/
 
 Please reconsider updating this library accordingly
