### ISSUE TITLE
Why don't you support to get PayPal from Nonce

### ISSUE THREAD

**Issue by napoleonit76** [braintree/braintree_php#142]
The official documentation doesn't mention about how to get the card instance by nonce. But I've read the source code and found that you guys has exposed the function `fromNonce` to retrieve it by `nonce`. Why don't you do the same thing for PayPal account? Obviously we can do that by following the way you treat to CreditCard, but I think it's better if it is an official stuff from the right-owner.

**Comment by omgrr** [comment]
The `fromNonce` method you are looking at in the source is deprecated. The new way to create a payment method is by using [`PaymentMethod#create`](https://developers.braintreepayments.com/guides/payment-methods/php#create).

If you have more questions about your integration I would reach out to [support](https://support.braintreepayments.com).
