### ISSUE TITLE
Cannot solve this SSL Validation issue. Any ideas?

### ISSUE THREAD

**Issue by j-mcnally** [braintree/braintree_php#143]
[Fri Jun 24 18:12:11 2016] 127.0.0.1:58113 [200]: / - Uncaught exception 'Braintree\Exception\SSLCertificate' in /Users/jmcnally/projects/braintree_php_example/vendor/braintree/braintree_php/lib/Braintree/Http.php:152
Stack trace:
#0 /Users/jmcnally/projects/braintree_php_example/vendor/braintree/braintree_php/lib/Braintree/Http.php(101): Braintree\Http->_doUrlRequest('POST', 'https://api.san...', '<?xml version="...')
#1 /Users/jmcnally/projects/braintree_php_example/vendor/braintree/braintree_php/lib/Braintree/Http.php(42): Braintree\Http->_doRequest('POST', '/merchants/fbyn...', '<?xml version="...')
#2 /Users/jmcnally/projects/braintree_php_example/vendor/braintree/braintree_php/lib/Braintree/ClientTokenGateway.php(61): Braintree\Http->post('/merchants/fbyn...', Array)
#3 /Users/jmcnally/projects/braintree_php_example/vendor/braintree/braintree_php/lib/Braintree/ClientTokenGateway.php(47): Braintree\ClientTokenGateway->_doGenerate('/client_token', Array)
#4 /Users/jmcnally/projects/braintree_php_example/vendor/braintree/braintree_php/lib/Braintree/ClientToke in /Users/jmcnally/projects/braintree_php_example/vendor/braintree/braintree_php/lib/Braintree/Http.php on line 152

**Comment by raymondberg** [comment]
@j-mcnally This would require a lot more information to begin solving. I would recommend you contact [Braintree support](https://support.braintreepayments.com) as Github isn't ideal for debugging issues involving private data.

**Comment by j-mcnally** [comment]
Well honestly its not private data afaik, it seems to be an issue with php and ssl.
