### ISSUE TITLE
Get One Braintree_Plan

### ISSUE THREAD

**Issue by Bordovsky** [braintree/braintree_php#145]
Hello,
I am looking for way to check my billing informations with informations set in Braintree billing plan. Is it possible to get one plan from Braintree directly? I have plan id, obtain all plans via Braintree_Plan::all() and then walk through them and check id. In future it would be terrible way of doing this.

Is there any chance that something as Braintree_Plan::get(string $plan_id) would show up? Or is there any chance to get single plan some different way?

**Comment by mtmarsh3** [comment]
Hi Bordovsky,

Currently there is no way of getting a single plan from Braintree. You are doing the correct logic of grabbing all plans, then picking the relevant plan from the group using its id. The intended use case is to have a few base plans and create subscriptions that override specific attributes in those plans that would need slight variations.

**Comment by Bordovsky** [comment]
Thank you for response. 
Overwriting few plans should be manageable.  I am closing the issue now.

But I still wander, why some plan has to be made when majority of subscription parameters can be rewritten? Discounts and Add-ons aside:
Price
Trial duration and trial duration unit
Start date
Number of billing cycles
are parameters that may be overwritten. That leaves only currency, billing cycle and description. Why is not possible specify those too and work without plans?

**Comment by pblesi** [comment]
Hi @Bordovsky 

The reason those are not able to be specified is that they provide a cohesive way to tie together groups of of subscriptions into a specific plan. This is the way we modeled it to mirror common usage for our merchants.
