### ISSUE TITLE
failOnDuplicatePaymentMethod

### ISSUE THREAD

**Issue by sepych** [braintree/braintree_php#146]
I'm getting exception with customer->update() function:

object(InvalidArgumentException)#59 (7) {
  ["message":protected]=>
  string(63) "invalid keys: creditCard[options][failOnDuplicatePaymentMethod]"
  ["string":"Exception":private]=>
  string(0) ""
  ["code":protected]=>
  int(0)
  ["file":protected]=>
  string(52) "/var/www/tutdev/src/braintree/lib/Braintree/Util.php"
  ["line":protected]=>
  int(344)
  ["trace":"Exception":private]=>
  array(12) {
    [0]=>
    array(6) {
      ["file"]=>
      string(63) "/var/www/tutdev/src/braintree/lib/Braintree/CustomerGateway.php"
      ["line"]=>
      int(340)
      ["function"]=>
      string(10) "verifyKeys"
      ["class"]=>
      string(14) "Braintree\Util"
      ...

**Comment by raymondberg** [comment]
Thanks for reporting this, @sepych! You are correct, the client library does indeed prevent the submission of that option. We are working to correct this and will reach out to you as soon as we have a fix.

**Comment by jackellenberger** [comment]
Hi @sepych,

We have completed our fix for this in all of the client libraries, and it will be available with our next release. Sorry for the delay!
