### ISSUE TITLE
Slow querying of transaction

### ISSUE THREAD

**Issue by jobbrown** [braintree/braintree_php#150]
In short, I am trying to get all transaction in the past week to get a total per merchant but the speed of this is really slow. 

An average week takes me 135 seconds to download. Currently, this is pulling down just over 2000 transactions. 

I use the following code: 

```php
// This just runs Braintree_Configuration::environment/merchantId etc
$this->setUpBraintree('IGD');
 
$from = date("m/d/Y H:i", strtotime('2016-09-26 00:00:00'));
$to = date("m/d/Y H:i", strtotime('2016-10-02 23:59:59'));
 
// Start timer
$start = microtime(true);
 
$collection = Braintree_Transaction::search([
    // All the order statuses we want
    Braintree_TransactionSearch::status()->in([
        Braintree_Transaction::AUTHORIZED,
        Braintree_Transaction::SETTLED,
        Braintree_Transaction::SETTLING,
        Braintree_Transaction::SUBMITTED_FOR_SETTLEMENT,
        Braintree_Transaction::SETTLEMENT_PENDING
    ]),
 
    // The dates we want
    Braintree_TransactionSearch::settledAt()->between($from, $to),
]);
 
$orders = [];
 
// Loop over transaction to pull them all out
foreach($collection AS $coll) {
    $orders[] = $coll;
}
 
echo 'Total time: ' . (microtime(true) - $start);
```

Is there we can speed this process up? 

I've tried increasing with the pager size. Currently this is hard coded to be whatever the API sends back in `ResourceCollection.php`. Is there a reason its being forced to be so slow? As shown below, from my initial tests this isn't helping the situation. 

```
50 (default): 135 seconds
100: 68 seconds
500: 19 seconds
1000: 12 seconds
2100 (to allow a single request on my data set): 4.95 seconds  
```

**Comment by jackellenberger** [comment]
Hi @jobbrown,

To my knowledge there is nothing that should be rate-limiting this query or artificially slowing it down. My recommendation is to contact [support](mailto:support@braintreepayments.com) and pass along your merchant id and the above query. They should be able to take a look at your vault and make a deduction about what is causing this call to go so long. 

I am going to close this issue as the long query time is doubtlessly happening on the Gateway side, rather than within the client library itself.

**Comment by jobbrown** [comment]
Thanks @jackellenberger 

I reached out to support again and they gave a little insight into the decision.

> In this case, by increasing the page size you are effectively reducing the number of API requests to the gateway, which is why you are seeing the request complete in a shorter time. This is because the amount of records you are returning can be gathered before the request times out. 

> However, while this works in this specific case, it would not work in many merchant use-cases in which we do not know the maximum amount of records that will need to be returned. For this reason, we've settled on a page size that will allow most merchants to return their records in a single call (meaning more requests, but a much lower chance that any particular request for a page will time out.) 

Any possibility of making this overridable in the future? Would prefer to avoid having to fork the repo as we'll eventually fall behind on updates.

**Comment by bensebborn** [comment]
+1 on this.

We query a day's transactions, around 2-3000 and it takes forever. Being able to efficiently query this faster will make a massive difference to us.

**Comment by jobbrown** [comment]
I got the following response from support back when I was looking at this...

```
In this case, by increasing the page size you are effectively reducing the number of API requests to the gateway, which is why you are seeing the request complete in a shorter time. This is because the amount of records you are returning can be gathered before the request times out. 

However, while this works in this specific case, it would not work in many merchant use-cases in which we do not know the maximum amount of records that will need to be returned. For this reason, we've settled on a page size that will allow most merchants to return their records in a single call (meaning more requests, but a much lower chance that any particular request for a page will time out.) 
```

Appreciate this limit has been set with smaller merchants in mind but it means going on 50 API calls for larger merchants each time we want to do this.

**Comment by bensebborn** [comment]
@jobbrown Could you let me know how you manually overrode the page size as I really need to adjust this while a fix is implemented.

I presume you're looking at 

    $this->_pageSize = $response["searchResults"]["pageSize"];


However If I change this to say 2000, I only get 100 results back?

**Comment by jobbrown** [comment]
@bensebborn 

Honestly.. no idea. 

When writing my e-mails to support / opening this Issue I tinkered with the code but didn't save it but definitely had it running 2k records (to get the timings). When I forked it to swap the code out I couldn't get it replicating the behaviour. 

Let me have another look and see if I can get it working. I gave up pretty quickly after forking it as I had other stuff on.

**Comment by bensebborn** [comment]
Thanks @jobbrown Let me know if you come up with anything,

Would be great to get this configurable as 50 records at a time, when querying 2000 records means 40 roundtrips over SSL.. no wonder it's slow.

**Comment by jobbrown** [comment]
@bensebborn It feels like somethings changed on the server side to ignore the clients requested pageSize. It's either that or I was being stupid and printing out `$ids` and not actual transactions...

If you print out `$response` in `TransactionGateway@fetch` you'll see

```
public function fetch($query, $ids)
    {
        $criteria = [];
        foreach ($query as $term) {
            $criteria[$term->name] = $term->toparam();
        }
        $criteria["ids"] = TransactionSearch::ids()->in($ids)->toparam();
        $path = $this->_config->merchantPath() . '/transactions/advanced_search';
        $response = $this->_http->post($path, ['search' => $criteria]);
        dd($response);
        return Util::extractattributeasarray(
            $response['creditCardTransactions'],
            'transaction'
        );
    }
```

Result ...

```
array:1 [▼
  "creditCardTransactions" => array:4 [▼
    "currentPageNumber" => array:1 [▶]
    "pageSize" => array:1 [▼
      0 => 50
    ]
    "totalItems" => array:1 [▼
      0 => 692
    ]
    "transaction" => array:50 [▶]
  ]
]
```

**Comment by bensebborn** [comment]
Cheers.

I've just opened this as a new issue, hopefully we can get some movement on it

#153
