### ISSUE TITLE
Google App Engine PHP55 Error

### ISSUE THREAD

**Issue by keoir** [braintree/braintree_php#152]
We are having issues with the SDK on Google App Engine Standard Environment w/ PHP55.

Getting the following when trying to use the SDK in the code base to process a transaction.

Warning: DOMDocument::loadXML(): Start tag expected, '<' not found in Entity, line: 1 in /base/data/home/apps/s~attendle-1050/2.396568182706286395/assets/ext/braintree/lib/Braintree/Xml/Parser.php on line 28 Notice: Trying to get property of non-object in /base/data/home/apps/s~attendle-1050/2.396568182706286395/assets/ext/braintree/lib/Braintree/Xml/Parser.php on line 30 Fatal error: Call to a member function hasChildNodes() on a non-object in /base/data/home/apps/s~attendle-1050/2.396568182706286395/assets/ext/braintree/lib/Braintree/Xml/Parser.php on line 118

With that, we ran some test and found the error is caused by the $xml going into lib/Braintree/Xml/Parser.php is getting encrypted data instead of a XML string.

We are using curl.so, and disabling libxml_disable_entity_loader with setting it to false with no anvil to fixing this on our own.

This is currently affecting live transactions, so we would like to get it fixed rather soon.

**Comment by keoir** [comment]
Fixed, future reference.
-----
Comment Out, Line 110:curl_setopt($curl, CURLOPT_ENCODING, 'gzip'); in Http.php on app-engine. App Engine, automaticly encodes all content and request with gzip for performance.

**Comment by jackellenberger** [comment]
Hi @keoir,

We're glad to hear that you found the source of the problem! I'm going to close this issue, but of course if anything else comes up just let us know or get in contact with [Braintree support](mailto:support@braintreepayments.com).

In the future, we'd absolutely recommend having a [sandbox environment](https://www.braintreepayments.com/sandbox) set up to catch things like this before they interfere with live transactions. We have [instructions](https://developers.braintreepayments.com/start/go-live/php) posted to help migrate to production when everything is in place.
