### ISSUE TITLE
Move the `class_alias` in an other place

### ISSUE THREAD

**Issue by Taluu** [braintree/braintree_php#154]
As you are supporting both psr-0 pear style and psr-4, your classes all look like `Braintree\\...`, while you have `class_alias`es to match the old psr-0 style. so far, so good.

BUT, if you use composer in an optimized way (with the `-a` flag), as it scans the classes, so it finds the `Braintree\\...` classes... but not the `Braintree_` classes, as these are aliases declared in each classes (This is another caveat of #129 btw). As it scans the classes, it cannot then "search" the classes with a psr-0 prefix, as the goal is to optimize and avoid to get through that step.

Multiple solutions exists ; change the examples (there is no value whatsoever, except getting developpers (like us) getting lost on which class we should use, we had no idea why our app was not finding the class `Braintree_Configuration` while it should search for `Braintree\Configuration`... BC is great, but *useful* and *functionnal* BC is better).

Another solution would be to have these `class_alias` declared in another file, included at runtime, but the thing is, this would load all classes, which is not great either. Another solution would be to have your own autoloader, but that would defeat the purpose of using composer...

**Comment by danakatz** [comment]
Thank you for letting us know about this issue, @Taluu! We added a clarification in the README noting that that flag requires PSR-4 namespacing.
