### ISSUE TITLE
Search by disputeDate gives error

### ISSUE THREAD

**Issue by UbaDeveloper** [braintree/braintree_php#155]
After import the Braintree SDK:

```
Braintree_Configuration::environment('production');
Braintree_Configuration::merchantId('merchatId');
Braintree_Configuration::publicKey('publicKey');
Braintree_Configuration::privateKey('privateKey');
```

And trying to fetch the transactions that have been disputed:
```
$now = new Datetime();
$collection = Braintree_Transaction::search([
  Braintree_TransactionSearch::status()->in([
    Braintree_TransactionSearch::disputeDate()->lessThanOrEqualTo($now)
  ])
]);
```
According to [https://developers.braintreepayments.com/reference/request/transaction/search/php#dispute-date](https://developers.braintreepayments.com/reference/request/transaction/search/php#dispute-date)

This gives me the following error:

`Object of class Braintree\RangeNode could not be converted to string in /braintree-php/lib/Braintree/MultipleValueNode.php on line 17`

I originally tried with the 3.16.0 version but had no luck with the current version.

**Comment by danakatz** [comment]
Hi @UbaDeveloper,

Your code snippet differs slightly from the documentation you cited — it has the dispute date search nested inside a separate status search. To find transactions that have been disputed, follow the documentation example exactly:

```php
$now = new Datetime();
$collection = Braintree_Transaction::search([
  Braintree_TransactionSearch::disputeDate()->lessThanOrEqualTo($now)
]);
```

The `in` operator in this case expects an array of [transaction statuses](https://github.com/braintree/braintree_php/blob/master/lib/Braintree/Transaction.php#L176-L190), but in your code you send another transaction search, which causes the conversion error you're seeing. To find transactions with a particular status, follow [this example](https://developers.braintreepayments.com/reference/general/searching/search-fields/php#multiple-value-fields):

```php
$collection = Braintree_Transaction::search([
  Braintree_TransactionSearch::status()->in(
    [
      Braintree_Transaction::GATEWAY_REJECTED,
      Braintree_Transaction::SETTLED
    ]
  )
]);
```

You could also combine these two searches, but make sure they are not improperly nested:

```php
$collection = Braintree_Transaction::search([
  Braintree_TransactionSearch::disputeDate()->lessThanOrEqualTo($now),
  Braintree_TransactionSearch::status()->in(
    [
      Braintree_Transaction::GATEWAY_REJECTED,
      Braintree_Transaction::SETTLED
    ]
  )
]);
```

Feel free to reach out to [Braintree support](mailto:support@braintreepayments.com) with any further questions!

**Comment by UbaDeveloper** [comment]
Oh, i see. My bad.

Thanks. I'll try it as soon I can.
