### ISSUE TITLE
App Engine PHP Curl doesn't decompress gziped data

### ISSUE THREAD

**Issue by Taracque** [braintree/braintree_php#156]
It seems that google's curl implementation doesn't uncompress gzip-ed data.
Because of that, Braintree/Http->_doUrlRequest gots the gzip-ed data in the $response, which makes further processing impossible.

Inserting the following code just before the return statement decompress the data if gzip header is found.

> $offset = 0;
> if (substr($response,0,2) == "\x1f\x8b") $offset = 2;
> if (substr($response,$offset,1) == "\x08") $response = gzinflate(substr($response, $offset + 8));

**Comment by danakatz** [comment]
Hi @Taracque,

We’ll consider handling this behavior in the library, and in the meantime it sounds like you have a solution that works for you (see #152 for another option). Thanks for the suggestion!

**Comment by Taracque** [comment]
Do you want me to send a post request for that, or the above snippet is enough? (It simply checks if the response starts with a gzip header and sends a gzinflate over it)

**Comment by danakatz** [comment]
No need to submit a PR - the snippet will help as we explore the best way to implement and test this internally. Thanks!

**Comment by bluk** [comment]
Starting in version 3.22.0, you can [disable the gzip encoding](https://github.com/braintree/braintree_php#google-app-engine) by setting the `Braintree\Configuration::acceptGzipEncoding(false);` configuration option. This was considered the safer option for more environments. Hope that helps!
