### ISSUE TITLE
Implement JsonSerializable interface to allow for encoding of protected vars?

### ISSUE THREAD

**Issue by jacobsee** [braintree/braintree_php#157]
After a call originating from an AJAX request such as
```
    $result = Braintree_Customer::update(
      $customer->id,
      [
        'creditCard' => [
          'paymentMethodNonce' => $nonce
        ]
      ]
    );
```
It would be nice to be able to pass some of the information from the `$result->customer` object back to the client as an AJAX response, which would require JSON encoding with `json_encode()`. This encoding returns `{}` due to the protected variables in the object. Would it be a security issue to implement `JsonSerializable` to allow this to happen? If not, I may fork and try to implement it.

**Comment by jacobsee** [comment]
Implemented this for what appear to be key classes in braintree/braintree_php/#159. 
Feedback on whether allowing encoding of these variables presents a security issue or not still welcome...

**Comment by danakatz** [comment]
Closing this issue for the reasons outlined in #159.
