### ISSUE TITLE
php curl Explicitly set CURLOPT_SSLVERSION

### ISSUE THREAD

**Issue by blasto333** [braintree/braintree_php#160]
In cent OS 6 (some versions) even if curl tls 1.2 is available the default behavior is to NOT use this. If in curl you set the following; then it will work. I

    curl_setopt($curl, CURLOPT_SSLVERSION, 6);

I think any curl calls in the php library should do this to ensure greatest compatibility

SEE:
https://github.com/curl/curl/issues/700

**Comment by bluk** [comment]
Starting in [3.21.0](https://github.com/braintree/braintree_php/blob/master/CHANGELOG.md#3210), released today, you can set an explicit SSL version on your Braintree configuration object.

```php
Braintree\Configuration::sslVersion(6);
```

We appreciate your patience! Let us know if you run into any other issues.
