### ISSUE TITLE
Getting Error "Braintree_Exception_SSLCertificate"

### ISSUE THREAD

**Issue by pradeepkhadka** [braintree/braintree_php#163]
I am using Braintree payment method since last 2 year. Its working perfect, but now there some issue with sandbox environment. it's throw an error "Braintree_Exception_SSLCertificate" Although same source code working perfect on production.
 Please suggestion me the cause of this error and how i can fix it.

**Comment by lkorth** [comment]
The Braintree sandbox has been [updated to require TLS 1.2](https://www.braintreepayments.com/blog/updating-your-production-environment-to-support-tlsv1-2/). It appears that your server is failing to communicate using TLS 1.2.

To verify and troubleshoot your issue please take a look at the [TLS update documentation](https://github.com/paypal/TLS-update#php).

**Comment by goelectricstations** [comment]
Same issue. No issue with production

**Comment by goelectricstations** [comment]
thank you, fixed with this: https://github.com/braintree/braintree_php/pull/161/commits/f47b73e03e667eed3332a36ca3005ecfa66b74ba

**Comment by bluk** [comment]
Starting in [3.21.0](https://github.com/braintree/braintree_php/blob/master/CHANGELOG.md#3210), released today, you can set an explicit SSL version on your Braintree configuration object.

```php
Braintree\Configuration::sslVersion(6);
```

We appreciate your patience! Let us know if you run into any other issues.

**Comment by goelectricstations** [comment]
@bluk  when will be avaliable the version 3.21.0 on the website?

**Comment by bluk** [comment]
@goelectricstations [3.21.1](https://developers.braintreepayments.com/start/hello-server/php) is now available on the website. Sorry for the delay.

**Comment by PrakashLakhara** [comment]
In my case, Braintree was not able to find cert file.
I used curl_errno for finding this issue.

**Comment by tarun90** [comment]
> In my case, Braintree was not able to find cert file.
> I used curl_errno for finding this issue.

this is really helpful for me thanks.
