### ISSUE TITLE
Fatal error: Uncaught exception 'Braintree_Exception_SSLCertificate' 

### ISSUE THREAD

**Issue by bhavinrana07** [braintree/braintree_php#166]
`Fatal error: Uncaught exception 'Braintree_Exception_SSLCertificate' in /Users/`

trying to test the braintree with php lib on my localhost, but it says following, (i user mac with mamp).
any once with same problem or any Braintree Engineer here. what is the Solution for this on localhost. it works fine with SSL on my staging server.

**Comment by bluk** [comment]
This could be an environment issue with using TLS 1.2 communicating with sandbox. Please see the [PayPal TLS update repository](https://github.com/paypal/TLS-update#php) for some suggestions and a test script to check that your localhost environment works with TLS 1.2.

**Comment by treeslikemedia** [comment]
This just started happening for me too, after months of running the Braintree PHP lib on MAMP with no problems at all.

**Comment by bluk** [comment]
@treeslikemedia Is this in the sandbox environment or in the production environment? Please try the suggestions in the PayPal TLS update repository to ensure your environment is compatible.

The sandbox environment was recently upgraded to support only TLS 1.2 connections. The production environment will be updated some time later this year. Please see [this Braintree blog post](https://www.braintreepayments.com/blog/updating-your-production-environment-to-support-tlsv1-2/) for more details.

**Comment by typeslower** [comment]
Yeah I was running into the same issue with MAMP Pro 3.5 earlier. Upgraded to 4.0 and it comes with an option to issue certificates beyond TLS 1.0. That worked for me.

**Comment by EvanHahn** [comment]
It looks like this issue was solved. Do y'all mind if we close this issue?

**Comment by bhavinrana07** [comment]
**solution** : for localhost update your wamp/ Mamp /Server to reach the latest environment requirements. please find the links as above comments.  thanks guys.
