### ISSUE TITLE
Wehbooks is not working.

### ISSUE THREAD

**Issue by prakashmalviya** [braintree/braintree_php#177]
Hi,
### General information

* SDK/Library version: 3.23.0
* Environment: Production
* Language, language version, and OS: Laravel 5.2, Ubuntu 15.10

### Issue description

I'm getting below error on webhooks.

**_InvalidSignature in WebhookNotificationGateway.php line 16:
payload contains illegal characters_**

I have contacted braintree support and they reply me with below details:

Thank you for following up with code samples. After taking a look, I think we may have found the cause of the 500 error. 

In your handleWebhook function (line 20) and the parseBraintreeNotification​ function (line 43), you are parsing the webhook and wrapping it into the framework's `Request` object. It is very likely that the framework is adding illegal characters to payload. We generally do not recommend manipulating the incoming payload at all. In order to POST the webhook without any errors, here is the code snippet that Collin provided in his previous email:

```
$webhookNotification = Braintree_WebhookNotification::parse(         
  $_POST["bt_signature"], $_POST["bt_payload"]     
); $webhookNotification->kind; 
# => "subscription_went_past_due"


$webhookNotification->timestamp; 
# => Sun Jan 1 00:00:00 UTC 2012
```

Once you have the Webhook Notification, you can draft a message or use it in your code in other ways:

```
$message =         
  "[Webhook Received " . $webhookNotification->timestamp->format('Y-m-d H:i:s') . "] "         
  . "Kind: " . $webhookNotification->kind . " | ";     
  
file_put_contents("/tmp/webhook.log", $message, FILE_APPEND); }
```

If you POST the webhook directly without any manipulation, you should not run into any others. Please let me know if you have any questions and feel free to reach out if you run into other issues.

**Comment by sdcoffey** [comment]
Hey @prakashmalviya,

Thanks for submitting this report. If I'm reading this correctly, it looks like Braintree support gave you some suggestions for how to fix the error you were running in to. Were you able to implement those suggestions successfully?

**Comment by prakashmalviya** [comment]
Hi @sdcoffey,

They have simply suggested like instead of Laravel request object we have to use $_POST, I have tried and on suggested method but still, have the same issue.

Have you tried any webhooks so far?

**Comment by sdcoffey** [comment]
@prakashmalviya,

Can you provide us with a snippet of what your webhook parsing code looks like so we can debug further?

**Comment by prakashmalviya** [comment]
Hi @sdcoffey,

Here if your requested files, PFA

**Comment by prakashmalviya** [comment]
`/**
		 * Handle a Braintree webhook call.
		 * @param  \Illuminate\Http\Request $request
		 * @return \Symfony\Component\HttpFoundation\Response
		 */
		public function handleWebhook(Request $request)
		{
			try {
				$webhook = $this->parseBraintreeNotification($request);
			}
			catch (Exception $e) {
				return;
			}
			$method = 'handle' . studly_case(str_replace('.', '_', $webhook->kind));
			if (method_exists($this, $method)) {
				return $this->{$method}($webhook);
			}
			else {
				return $this->missingMethod();
			}
		}`

`/**
		 * @param $webhook
		 * @return Response
		 */
		public function handleSubscriptionChargedSuccessfully($webhook)
		{
			$subscription = $this->getSubscriptionById($webhook->subscription->id);
			if ($subscription) {
				$user = User::findOrFail($subscription->user_id);
				$input = [
					'ends_at' => $webhook->subscription->billingPeriodEndDate
				];
				// Need to update membership end date on subscription table
				$this->subscriptionRepository->updateEndAt($input, $webhook->subscription->id);
				// We have to also maintain log and entry on transaction table for any future reference.
				$sales['user_id'] = $subscription->user_id;
				$sales['transaction_id'] = isset($webhook->subscription->id) ? $webhook->subscription->id : '';
				$sales['plan_id'] = config('config.plans.unlimited');
				$sales['status'] = 'authorized';
				$sales['type'] = 'subscription';
				$sales['amount'] = config('config.plans.bill-charges.MB_Unlimited');
				$this->salesTransactionsRepository->create($sales);
				Log::useFiles(storage_path() . '/logs/braintree_sale.log');
				Log::info('Transaction of user id: ' . $subscription->user_id . ' ON ' . date('Y-m-d H:i:s') . ' => Monthly Reoccurring');
				Log::useFiles(storage_path() . '/logs/braintree.log');
				Log::info('Success on handleSubscriptionChargedSuccessfully updated for id: ' . $subscription->user_id . ' ON ' . date('Y-m-d H:i:s'));
			}
			else {
				Log::useFiles(storage_path() . '/logs/braintree.log');
				Log::info('Error on handleSubscriptionChargedSuccessfully updated for id: ' . json_encode($webhook) . ' ON ' . date('Y-m-d H:i:s'));
			}
			return new Response('Webhook Handled', 200);
		}`

**Comment by sdcoffey** [comment]
Hey @prakashmalviya,

I've spoken with our support team, they're going to be following up with you about this. They'll let you know when and if it gets to a point where we should open another issue here. Thanks!
