### ISSUE TITLE
Missing line item description in PayPal-generated email when creating subscription

### ISSUE THREAD

**Issue by crmpicco** [braintree/braintree_php#178]
### General information

* SDK/Library version: 3.16
* Environment: Production
* Language, language version, and OS: PHP 7 on Ubuntu 16.04 LTS

### Issue description

I have an issue where the 'Description' field in my PayPal "You authorized a payment" email is coming through blank, as below:

![selection_357](https://cloud.githubusercontent.com/assets/2536923/25267856/0f688c70-26a9-11e7-80f3-623f3350883a.png)

I have put a support ticket in with Braintree, however they have said:

> ...we would be unable to confirm if/how the information passed would be reflected within any PayPal email to the customer. Since this is PayPal-specific functionality that lives outside of Braintree's API, we are unable to confirm with accuracy if this would work as needed. 

I am trying to ascertain what, if anything, I can pass through in the `$attributes` array in the `create` method to populate this field.

```
public static function create($attributes)
{
   return Configuration::gateway()->subscription()->create($attributes);
}
```
The [Braintree documentation](https://developers.braintreepayments.com/reference/request/subscription/create/php#dynamic-descriptors) suggests the descriptor field is for the entry on a credit card/bank statement and no the PayPal line item information.

Is there something I can pass through when creating a subscription to populate this field?

**Comment by sdcoffey** [comment]
Hey @crmpicco,

Thanks for the report - we currently don't support passing through a description for PayPal subscriptions, but it's something we can and will look into. If we determine it's feasible I'll drop an update here.

**Comment by crmpicco** [comment]
Thanks for the response @sdcoffey

**Comment by crookedneighbor** [comment]
We may add this in the future, but at this time, we're not going to add it to the SDK, so I'm going to close this issue.

**Comment by scyrma** [comment]
Just curious - I see there is a "Paypal description" item in the subscription::create call, as seen on https://developers.braintreepayments.com/reference/request/subscription/create/php#options.paypal

Was this added in the last few months and would it be the way to go for our issue here?

**Comment by bluk** [comment]
@scyrma Yes, it should solve your issue. This feature was added to this SDK in [version 3.26.0](https://github.com/braintree/braintree_php/blob/master/CHANGELOG.md#3260).
