### ISSUE TITLE
Lack of 3dSecure test nonces

### ISSUE THREAD

**Issue by joereynolds** [braintree/braintree_php#181]
We are trying to integrate 3dsecure payments into our payment service however we've noticed that there are no test nonces for 3dsecure transactions.
This causes all of our tests to fail with `"Gateway Rejected: three_d_secure"` as they are currently using the `"fake-valid-nonce"` test nonce.

Are there any plans to add these 3dsecure test nonces to the library or is there another way around it?

Thanks

**Comment by sdcoffey** [comment]
Hey @joereynolds,

I'm not sure which of these came first, but it looks like a member of our support team answered your question [here](http://stackoverflow.com/questions/43659532/unit-testing-3dsecure), so I'm going to close this. Please let us know if you're having any other issues with your integration.
