### ISSUE TITLE
SSL connect error

### ISSUE THREAD

**Issue by riccardomessineo** [braintree/braintree_php#182]
### General information

* SDK/Library version: 3.23.0
* Environment: sandbox
* Language, language version, and OS: PHP 5.6, Centos 6.5

### Issue description
Hi, 
  I'm facing a SSLcertificate Exception on our stage server.
On local dev (using sandbox) everything works fine, but on stage it throws this exception while generating a token: the Curl_errno is 35, SSL connect error.

Am I missing a library?
I'm using:
- CentOS 6.5
- httpd (Apache/2.2.15)
- curl 7.19.7
- OpenSSL 1.0.1e-fips 11 Feb 2013

**Comment by sdcoffey** [comment]
Hey @riccardomessineo,

Sorry for taking so long to get back with you. Just to clarify, you're having SSL issues connecting to Braintree Production in your staging environment?

**Comment by sdcoffey** [comment]
Hey @riccardomessineo,

I'm going to close this due to inactivity, please open a new issue if this is an issue you're still experiencing.
