### ISSUE TITLE
Eager load search transaction result

### ISSUE THREAD

**Issue by luqmanrom** [braintree/braintree_php#183]
### General information

* SDK/Library version: 3.6.0
* Environment: Sandbox
* Language, language version, and OS: PHP 7.0 MacOS Sierra 10.12

### Issue description

I am looking for a way to eager load the search transaction result. For now, it is lazy load referring to this [documentation](https://developers.braintreepayments.com/reference/general/searching/search-results/php). Is there any way to do it?

**Comment by sdcoffey** [comment]
Hey @luqmanrom,

There's currently no way to eager load results in the way you're describing. While this may change at some point, this is the way the behavior will remain for the foreseeable future. I'm going to close this, please let us know if you're having any other problems with the SDK!
