### ISSUE TITLE
$result->errors returning as null

### ISSUE THREAD

**Issue by crmpicco** [braintree/braintree_php#186]
### General information

* SDK/Library version: 3.23.1
* Environment: Production
* Language, language version, and OS: PHP 7 on Ubuntu 16.04 LTS

### Issue description

I am recently experiencing issues with calls to the Braintree API where `success` is not true, yes the `errors` attribute is null.

The error I get from the line with `$result->errors` on it is:
Error: Call to a member function deepAll() on null

This is a snippet of my code:
```
$result = Braintree\Subscription::update($subscription->id, [
   'addOns' => $addOns,
]);
if ($result->success) {
   // all good...          
} else {
   $errors = [];
   foreach($result->errors->deepAll() AS $error) {
      $errors[] = [$error->attribute => $error->code . ": " . $error->message];
   }
}
```
I don't think this error only applies to the `update` call.

The [documentation](https://developers.braintreepayments.com/reference/general/result-objects/php) states:

> The errors result object will only be populated if the error is due to a failed validation. In this case, the object will contain one or more validation errors indicating which parameters were invalid:

What is causing this and shouldn't `errors` always be set to something other than null? If not, what scenario would it be `null` (the docs don't confirm)?

**Comment by demerino** [comment]
@crmpicco The `errors` result object will only be populated if the error is due to a failed validation.

Refer to the [error results](https://developers.braintreepayments.com/reference/general/result-objects/php#error-results) documentation to see other reasons the request might not be successful. Let us know if you're still having issues.
