### ISSUE TITLE
How to add custom fields to subscriptions ?? I want to add a field called subscription Type?

### ISSUE THREAD

**Issue by ramdoss-anubavam** [braintree/braintree_php#188]
### General information

How to add custom fields to subscriptions ?? I want to add a field called subscription Type? is it possible to add in subscriptions ?

**Comment by demerino** [comment]
@ramdoss-anubavam Subscriptions don't support custom fields at this time.

As a workaround you can store the subscription id and the type in your database when you create the subscription.
