### ISSUE TITLE
create_function is deperecated

### ISSUE THREAD

**Issue by rinu** [braintree/braintree_php#191]
As of PHP 7.2, create_function is deprecated.
This is used in lib/Braintree/Util.php

**Comment by chrisdeeming** [comment]
I created a pull request to resolve this:

https://github.com/braintree/braintree_php/pull/193

**Comment by crookedneighbor** [comment]
Merged in with https://github.com/braintree/braintree_php/pull/193

This will go out in the next release. Thanks @chrisdeeming

**Comment by jaypatel512** [comment]
The fix is released in [v3.26.0](https://github.com/braintree/braintree_php/releases/tag/3.26.0). Please update your dependency now. Thank you for pointing out this issue.
