### ISSUE TITLE
SSL Connect error in Http.php on production server

### ISSUE THREAD

**Issue by dylanglockler** [braintree/braintree_php#194]
### General information

* SDK/Library version: 3.25.0
* Environment: Production (pre-release)
* Language, language version, and OS: PHP with Laravel 5.4 and Guzzle 6.3, CURL: 7.19.7, PHP 7.0.22

### Issue description

I have an application working well on my development server but when I move into production, with SSL, I get an SSL connect error (35) -this occurs in the Http.php file within braintree_php. Using a tokenization key I can retrieve a nonce and using braintree_php I have no program getting a nonce and performing all my application functions on the development server.  

The error occurs anywhere I attempt to generate a client token.

(2/2) ErrorExceptionSSL connect error (View: /var/www/vhosts/bryanallenevents.com/laravel-events/resources/views/openhouse/donation.blade.php)
--
in Http.php (line 187)

(1/2) SSLCertificateSSL connect error
--
in Http.php (line 187)

I took laravel out of the equation by creating a php test page to retrieve a clientToken 

`       require_once '/Volumes/Otto/Dylan/Sites/laravel-events/vendor/braintree/braintree_php/lib/Braintree.php';
		Braintree_Configuration::environment('sandbox');
		Braintree_Configuration::merchantId(xxxxxxxxx');
		Braintree_Configuration::publicKey('xxxxxxxxx');
		Braintree_Configuration::privateKey('xxxxxxxx');
		$clientToken = Braintree_ClientToken::generate();

		echo $clientToken;
`

On my dev machine it returns the token, on production, an error with Apache the stack trace:

mod_fcgid: stderr: PHP Fatal error: Uncaught Braintree\\Exception\\SSLCertificate: SSL connect error in /var/www/vhosts/bryanallenevents.com/laravel-events/vendor/braintree/braintree_php/lib/Braintree/Http.php:187

mod_fcgid: stderr: Stack trace:

mod_fcgid: stderr: #0 /var/www/vhosts/bryanallenevents.com/laravel-events/vendor/braintree/braintree_php/lib/Braintree/Http.php(114): Braintree\\Http->_doUrlRequest('POST', 'https://api.san...', '<?xml version="...', NULL)

mod_fcgid: stderr: #1 /var/www/vhosts/bryanallenevents.com/laravel-events/vendor/braintree/braintree_php/lib/Braintree/Http.php(45): Braintree\\Http->_doRequest('POST', '/merchants/m6rn...', '<?xml version="...')

mod_fcgid: stderr: #2 /var/www/vhosts/bryanallenevents.com/laravel-events/vendor/braintree/braintree_php/lib/Braintree/ClientTokenGateway.php(61): Braintree\\Http->post('/merchants/m6rn...', Array)

mod_fcgid: stderr: #3 /var/www/vhosts/bryanallenevents.com/laravel-events/vendor/braintree/braintree_php/lib/Braintree/ClientTokenGateway.php(47): Braintree\\ClientTokenGateway->_doGenerate('/client_token', Array)

mod_fcgid: stderr: #4 /var/www/vhosts/bryanallenevents.com/laravel-events/vendor/brain in /var/www/vhosts/bryanallenevents.com/laravel-events/vendor/braintree/braintree_php/lib/Braintree/Http.php on line 187

**Comment by crookedneighbor** [comment]
It's possible that your production server is not enabled correctly for TLS 1.2 (which the Sandbox environment requires). Can you follow these instructions to verify that your production server has the necessary updates? https://github.com/paypal/TLS-update#php

If you're still having issues after that, I recommend contacting our support team. This is unlikely to be an issue with the SDK itself.  https://developers.braintreepayments.com/forms/contact

Going to close this now, but feel free to comment if I'm incorrect and this is actually an issue with the SDK.
