### ISSUE TITLE
No fee returned by transaction sale?

### ISSUE THREAD

**Issue by echodreamz** [braintree/braintree_php#195]
### General information

* SDK/Library version: 3.25.0
* Environment: Both
* Language, language version, and OS: 7.0.23, CentOS 7, English

### Issue description

The associated processing fee does not seem to return back within Transaction::sale() or even the Transaction::find() methods.

Is this information not available? It would make life much easier if the API simply returned back the fee (much like paypal does).

**Comment by crookedneighbor** [comment]
The fees are not exposed via the API. You can get the fees by downloading your merchant statement. See https://articles.braintreepayments.com/support/control-panel/reporting/overview for more details.

**Comment by hypeJunction** [comment]
Why the secrecy? It would really help to have this information in the API. I brought this issue up several times with PayPal APIs, now seems that Braintree is following suit making it really difficult to maintain transaction transparency.

**Comment by crookedneighbor** [comment]
@hypeJunction this is not an SDK issue, if you have feedback about the API, I recommend contacting our support team: https://articles.braintreepayments.com/forms/contact

**Comment by echodreamz** [comment]
It is not a SDK issue directly no, it is a Braintree API issue that trickles down into the SDK issue.

**Comment by echodreamz** [comment]
Any changes to this? Even if the fee cannot be returned on the initial sale, is there a way to get the fee once a transaction completes?

**Comment by bradjones1** [comment]
@echodreamz This isn't an SDK issue.

**Comment by echodreamz** [comment]
I know... you can keep repeating it like parrot, but it doesnt change the fact that retrieving fees from the payment provider I use associated with transactions I conduct via said gateway is something the SDK could possibly be updated to support.

**Comment by bradjones1** [comment]
An SDK is not the same as the API. I encourage you to reach out to Braintree directly if you're unhappy with the API surface. Better yet, I think the maintainers would be well-advised to lock this discussion.

**Comment by hollabaq86** [comment]
👋 this is still only available via the [Control Panel](https://articles.braintreepayments.com/support/control-panel/reporting/overview). That said, I’m forwarding this feedback to our reporting team for consideration as a new feature to the API. This isn’t a guarantee that we will eventually have this available via the SDK, just that your very passionate request is forwarded to the right team 😄 

I’m also locking this issue. If you have any future questions, please [contact Support](https://articles.braintreepayments.com/forms/contact).
