### ISSUE TITLE
Card verification not run when creating payment method

### ISSUE THREAD

**Issue by ShaunDychko** [braintree/braintree_php#196]
### General information

* SDK/Library version: 3.25.0
* Environment: Sandbox
* Language, language version, and OS: PHP 7.1.1 on macOS

### Issue description

When creating a payment method using a testing card number for which a "processor_declined" error is supposed to occur, the result is nevertheless successful. I created the payment method using:
```
    $payload = [
      'customerId' => $customer->id,
      //        'paymentMethodNonce' => 'fake-processor-declined-visa-nonce',
      'paymentMethodNonce' => $nonce,
      'options' => [
        'makeDefault' => TRUE,
        'verifyCard' => TRUE,
      ],
    ];
    $response = PaymentMethod::create($payload);
```
with a nonce generated by the Drop-in UI with card number 4000 1111 1111 1115, from the list of testing numbers that should decline: https://developers.braintreepayments.com/reference/general/testing/php#unsuccessful-credit-card-verification.

When I use the `fake-processor-declined-visa-nonce` instead of the nonce created by the Drop-in UI, `$response->success == FALSE` as expected.

When creating a new customer with the Drop-in generated nonce, and card verification set to `true`, it fails as expected, which is inconsistent with the `PaymentMethod::create()` function here.

What I want is for the payment method creation to return `$result->success == FALSE` when using a card for which verification fails.

**Comment by ShaunDychko** [comment]
From Braintree support:

> If you would like the Drop-in UI to verify cards prior to the nonce being generated, you will need to pass the 'verifyCard' option within the ClientToken::generate() API request. Without passing this option specifically in the client token generate call, the Drop-in UI will actually immediately vault the payment method without verifying the information and pass the nonce back ready for creating the stored payment method.

**Comment by crookedneighbor** [comment]
Ahh, that makes sense. Thanks for reporting back!

**Comment by riteshkhatri** [comment]
> From Braintree support:
> 
> > If you would like the Drop-in UI to verify cards prior to the nonce being generated, you will need to pass the 'verifyCard' option within the ClientToken::generate() API request. Without passing this option specifically in the client token generate call, the Drop-in UI will actually immediately vault the payment method without verifying the information and pass the nonce back ready for creating the stored payment method.

Hi,
As you said using client token generate call by option verifyCard = true Drop-in UI will automatically check cvv verfication and do not store card into the vault but there is customer id required.
What if there is no customer ID, for the first time we are generating token to show drop-in Ui after that using nonce we can store the customer and we can get customer ID, then how to verify credit card first time?

**Comment by crookedneighbor** [comment]
@riteshkhatri our support team is the best place to get answers for your questions
