### ISSUE TITLE
Uploading shopping cart item details option ?

### ISSUE THREAD

**Issue by angular013** [braintree/braintree_php#197]
So the library is working fine. The issue i have is i am not able to find the PayPal cart upload option neither on client side ( javascript SDK ) nor o server side ( PHP SDK ). and i know this option is actually available on direct javascript express checkout integration provided by paypal. Cant seems to find in the braintree API reference docs also. Moreover how can we integrate our company logo with braintree javascript SDK ? because in paypal express checkout SDK , 'experience' field was given 

Below are some of the options given in direct paypal express checkout integration without braintree:

`            // payment() is called when the button is clicked
            payment: function(data, actions) {

                // Make a call to the REST api to create the payment
                return actions.payment.create({
                    payment: {
                                              
                        intent: "sale",						
						payer: {
							  payment_method: "paypal"
							  },							  
							  
                        transactions: [
						  {
							amount: {
							total: "30",  // this should be correct total amount(sum of below items) otherwise error will occur
							currency: "USD"
							},

						
							item_list: {
							items: [      // this is where php loop for items can be placed to loop over multiple items
							
							  {
							  name: "hat",
							  description: "Brown hat.",
							  quantity: "5",
							  price: "3",
							  sku: "SKUfvjdf",
							  currency: "USD"
							  },
											
							  {
							  name: "handbag", // shorthand for php echo
							  description: "Black handbag.",
							  quantity: "1",
							  price: "15",
							  sku: "SKUproduct34",
							  currency: "USD"
							  }
							]
							}
							
							
						  }
						  ],
						  
						  
						 note_to_payer: "Contact us for any questions on your order.",
						  redirect_urls: {
							  return_url: "http://www.google.com",  // this is called after successfull payment
							  cancel_url: "http://www.bta-mall.com" // this is called when user cancels payment
						  }
						  
                    },                                        
                    
                    experience: {
                        
                        name: "bta-mall",
                        presentation: {
                        logo_image: "https://tex03.000webhostapp.com//000_web/logos/bta-mall.png"
                        },
						input_fields: {
							no_shipping: 2
						}
                    }
                    
                    
                });
            },`

you can see that in 'item_list' we can pass cart details for paypal......and here is the braintree code:

` payment: function () {
				return paypalCheckoutInstance.createPayment({
				  // Your PayPal options here. For available options, see
				  // http://braintree.github.io/braintree-web/current/PayPalCheckout.html#createPayment
				  
				  flow: 'vault',  // 'checkout' or 'vault'
				  //amount: '10.00',
				  //currency: 'USD',
				  intent: 'sale',
				  
				 
				  
				  
				});
			  }`

i tried to use the same paramenter of direct paypal express checkout in the braintree javascript , but when   i checked the transaction in my merchant sandbox paypal account, only the amount was showing .

By the way this is my test server side code;

`// create a customer entry in the VAULT of the our braintree account
	$result = Braintree_Customer::create([
		'firstName' => 'Johnnn',
		'lastName' => 'Jones',
		'company' => 'Jones Co.',
		'paymentMethodNonce' => $_REQUEST['payload']['nonce']
	]);
	
	if ($result->success) {
		//echo($result->customer->id);
		//echo($result->customer->paymentMethods[0]->token);
		
		
		// make the transaction using the customer payment token
		$result = Braintree_Transaction::sale(
		  [
			'paymentMethodToken' => $result->customer->paymentMethods[0]->token,
			'amount' => '54.00',
			'options' => [
			'submitForSettlement' => true
			]
		  ]
		);

		if($result->success){
			
			
			echo "<h1>success</h1>";
			
			echo "<br><h1>Transaction Status: ".$result->transaction->status."</h1>";
			# e.g. 'submitted_for_settlement'

			echo "<br><h1>Transaction type: ".$result->transaction->type."<br><br></h1>";
			# e.g. 'credit'
			
		}else{
			
			echo "<pre>";
			var_dump($result);
			echo "</pre>";
			
		}
				
		
	} else {
		
		foreach($result->errors->deepAll() AS $error) {
			echo($error->code . ": " . $error->message . "\n");
		}
	}`

**Comment by angular013** [comment]
This is the picture , when the items are uploaded through direct paypal express checkout javascript code;

![image](https://user-images.githubusercontent.com/28813039/31182601-c1a9f77c-a93d-11e7-974c-d7003195ad88.png)

**Comment by bluk** [comment]
Support is being added for the PayPal line item transactions. There isn't an exact timeline, but it is coming soon.

The logo web experience profile feature is not supported. In the Braintree JS flow, the PayPal flow is in-context, and customers should still be able to see the merchant website in the background.

If you still have questions, please leave a comment and we can re-open or open a new issue. Thanks.

**Comment by angular013** [comment]
@bluk 

Do these fields be supported in the update ,these are available in direct express checkout javascript SDK;

`redirect_urls: {
						  return_url: "http://www.google.com",  // this is called after successfull payment
						  cancel_url: "http://www.bta-mall.com" // this is called when user cancels payment
					  }`


`input_fields: {
						no_shipping: 2
					}`

**Comment by crookedneighbor** [comment]
redirect and cancel url are not required for checkout.js, as everything happens in context and is never redirected to those urls.

I don't know about `input_fields`

**Comment by bluk** [comment]
The `no_shipping`: `2` value is not supported. `enableShippingAddress` is a similar field, but there is not a direct equivalent of the value's behavior.

**Comment by jazzpaths** [comment]
> Support is being added for the PayPal line item transactions. There isn't an exact timeline, but it is coming soon.
> 
> The logo web experience profile feature is not supported. In the Braintree JS flow, the PayPal flow is in-context, and customers should still be able to see the merchant website in the background.
> 
> If you still have questions, please leave a comment and we can re-open or open a new issue. Thanks.

That would be so helpful, it's not only about the customer seeing item details in background (which is more than enough, I agree), but PayPal does send a receipt after purchase and using PayPal with Braintree make the receipt missing the items the customer has payed for.

**Comment by dario-deromanis** [comment]
> That would be so helpful, it's not only about the customer seeing item details in background (which is more than enough, I agree), but PayPal does send a receipt after purchase and using PayPal with Braintree make the receipt missing the items the customer has payed for.

I agree with that
