### ISSUE TITLE
SSL error

### ISSUE THREAD

**Issue by Spoowy** [braintree/braintree_php#202]
Hello everyone,

is Braintree sandbox Api also working if ssl is turned off? What is the correct port(443?) when I want to connect to http://api.sandbox.bran...?

Or is it only possible to connect to https://api... I'm getting a TLS error on my localhost and ssl won't work(error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version).

What to do?

Cheers,
Erwin

**Comment by bluk** [comment]
Braintree requires `https`. Try looking at the [PayPal TLS Updates](https://github.com/paypal/TLS-update#php) for help, but it can depend on your PHP environment. Please feel free to contact [Braintree Support](https://developers.braintreepayments.com/forms/contact) for help.
