### ISSUE TITLE
Generate Checksum

### ISSUE THREAD

**Issue by risnaa** [braintree/braintree_php#203]
I have developed API in Laravel, now I have to generate only checksum which will be used with Android and IOS SDK.

Any help how to use your library to generate and return checksum will be very helpful.

Regards,
Avinash

**Comment by crookedneighbor** [comment]
I'm a little confused by your question. Are you asking [how to generate a client token](https://developers.braintreepayments.com/reference/request/client-token/generate/php)?

**Comment by crookedneighbor** [comment]
Going to close this for now, but feel free to comment with clarification about what you're asking.
