### ISSUE TITLE
HTTP Basic: Access denied.

### ISSUE THREAD

**Issue by postadelmaga** [braintree/braintree_php#204]
I just updated Braintree PHP library to 3.19 on my Magento store, I was 2.37 before. 
( It think TLS was not updated on that version, anyway It was working fine. ) 

The issue that now every time I do a Curl request I got _HTTP Basic: Access denied._
This is happening on my staging site (sandbox mode) on this call: _Braintree_Customer::find($id)_

Apparently the Lib works well and the SSL certificate has been found, I am not sure what-else I can check.

Note:
In ver 2.37 there were 2 ca certificates 

- api_braintreegateway_com.ca.crt
- sandbox_braintreegateway_com.ca.crt ( this it not present in ver. 3.19 )

Can I delete the second certificate ? it looks it is never used in the code.

**Comment by postadelmaga** [comment]
This was actually cause by wrong authentication values (user/pwd ) on staging

**Comment by crookedneighbor** [comment]
👍
