### ISSUE TITLE
invalid keys: options[three_d_secure][required]

### ISSUE THREAD

**Issue by postadelmaga** [braintree/braintree_php#205]
Hi,
This is a kind of urgent because it is on live site.

After updating to last version I got this error:

> exception 'InvalidArgumentException' with message 'invalid keys: options[three_d_secure][required]' in /var/www/clients/client2/web2/web/lib/Braintree/Util.php:329
> Stack trace:
> #0 /var/www/clients/client2/web2/web/lib/Braintree/TransactionGateway.php(44): Braintree\Util::verifyKeys(Array, Array)
> #1 /var/www/clients/client2/web2/web/lib/Braintree/TransactionGateway.php(268): Braintree\TransactionGateway->create(Array)
> #2 /var/www/clients/client2/web2/web/lib/Braintree/Transaction.php(485): Braintree\TransactionGateway->sale(Array)
> #3 /var/www/clients/client2/web2/web/app/code/local/Braintree/Payments/Model/Paymentmethod.php(114): Braintree\Transaction::sale(Array)

**Comment by crookedneighbor** [comment]
What version did you upgrade to? This bug was present in v3.20.0 and fixed in v3.20.1 https://github.com/braintree/braintree_php/blob/master/CHANGELOG.md#3211

**Comment by crookedneighbor** [comment]
I'm certain that your issue will be resolved if you upgrade to the latest version. I'm going to close this now, but comment here if you need additional help.
