### ISSUE TITLE
Braintree Sale Transaction is Working

### ISSUE THREAD

**Issue by vickygillsf** [braintree/braintree_php#208]
### General information

* SDK/Library version: Latest 
* Environment: Is this issue in Production
* Language, PHP

Firstly, I am creating a sub_merchant for payment, then, I want to make a transaction, but when I am going to Create a Sale Transaction, I am getting is currently unable to handle this request. HTTP ERROR 500 I am using this Code.

```
$mid = $result->merchantAccount->id;
    $res = Braintree_Transaction::sale([
      'merchantAccountId' =>$mid,
      'amount' => $amount, 
      'paymentMethodNonce' => $nonce,
      'serviceFeeAmount' => $serviceFeeAmount
    ]);
```

**Comment by bluk** [comment]
Please contact [Braintree Support](https://developers.braintreepayments.com/forms/contact) for help with your integration.

**Comment by dipen-apptrait** [comment]
I am facing same issue. How did you fix it?

**Comment by crookedneighbor** [comment]
@dipen-apptrait Please contact [Braintree Support](https://developers.braintreepayments.com/forms/contact) for help with your integration.
