### ISSUE TITLE
IS this library are in codeigniter

### ISSUE THREAD

**Issue by UMDEVELOPER** [braintree/braintree_php#221]
IS this library are in codeigniter

**Comment by crookedneighbor** [comment]
Braintree should be compatible in the Codeigniter framework. 

With some quick Googling, I found a 3rd party developer who has provided a wrapper to use Braintree with Codeigniter. https://github.com/AeonDave/CodeIgniter-Braintree-Lib

**Comment by crookedneighbor** [comment]
True. I did not look that closely at the wrapper, but you should be able to use it as an example for integrating with codeigniter.
