### ISSUE TITLE
validation error in payment 

### ISSUE THREAD

**Issue by UMDEVELOPER** [braintree/braintree_php#223]
I am follow your code and face this error
how can i solve this

> Validation errors: Array ( [0] => Braintree\Error\Validation Object ( [_attribute:Braintree\Error\Validation:private] => paymentMethodNonce [_code:Braintree\Error\Validation:private] => 91565 [_message:Braintree\Error\Validation:private] => Unknown or expired paymentMethodNonce. ) )

**Comment by crookedneighbor** [comment]
Again, please reach out to our support team for help with your integration: https://articles.braintreepayments.com/forms/contact

They are best equipped to look at the specifics of your integration and assist you.

This repo is for reporting issues with the SDK, not getting help with your integration.
