### ISSUE TITLE
Braintree\Exception\SSLCertificate : SSL certificate problem: unable to get local issuer certificate

### ISSUE THREAD

**Issue by notihnio** [braintree/braintree_php#229]
### General information

* SDK/Library version: 3.34.0
* Environment: Sandbox
* Language, language version, and OS: php7.2 Ubuntu 16.04.4 LTS (Laravel / Homestead)

### Issue description

When i call  \Braintree_PaymentMethodNonce::create($creditCardToken);

I receive 

Braintree\Exception\SSLCertificate : SSL certificate problem: unable to get local issuer certificate

**Comment by crookedneighbor** [comment]
I am unable to reproduce this.

```php
$result = Braintree_PaymentMethodNonce::create($creditCardToken);
print_r($result->paymentMethodNonce->nonce);
```

I don't think this is an issue with the SDK. Please [contact our support team](https://articles.braintreepayments.com/forms/contact) so we can better troubleshoot your integration.
