### ISSUE TITLE
No reply from salt team for integration with marketplace solution.

### ISSUE THREAD

**Issue by guesl** [braintree/braintree_php#233]
### General information

* 3.3.5 
* Environment: MacOS
* PHP 7.2 on Ubuntu 18

### Issue description
I am going to do integration with marketplace solution in my company platform.
I sent the email to sale team, but nothing response.
Do you have any idea to do the integration in other way?

Thanks.

**Comment by jackellenberger** [comment]
Hi @guesl, this is just a place to report technical bugs with the PHP SDK. 

To contact sales, visit [braintreepayments.com/contact/sales](https://www.braintreepayments.com/contact/sales), or to get help with an integration reach out to our [support team](https://developers.braintreepayments.com/forms/contact).
