### ISSUE TITLE
"PayPal pending payments are not supported"

### ISSUE THREAD

**Issue by breakline87** [braintree/braintree_php#235]
### General information

* SDK/Library version: 3.35.0
* Environment: Sandbox

### Issue description

Hello,

We're using a Linked PayPal account to test paypal payments. Everything is in sandbox mode. However when we're actually making the sale on the backend, the end result is:

"PayPal pending payments are not supported"

Here is how we make the sale on the server:

`$gateway = new Braintree\Gateway([
            'environment' => 'sandbox',
            'merchantId' => '3r4kzhswscznj32t',
            'publicKey' => '***',
            'privateKey' => '***'
        ]);

$result = $gateway->transaction()->sale([
            'amount' => $purchase->total_amount,
            'paymentMethodNonce' => $this->paypal_nounce,
            'options' => [
                'submitForSettlement' => True
            ]
        ]);
`

But this fails every time and we get a processing_declined error.

Why is this and is it an issue with the configration somewhere?

Thank you

**Comment by crookedneighbor** [comment]
Please contact our support team at https://articles.braintreepayments.com/forms/contact

They will be better equipped to examine your PayPal account see what is misconfigured. 

In a previous Github issue, this was the solution: https://github.com/braintree/braintree-web-drop-in/issues/161#issuecomment-301501211

Your account may have similar configuration issues. Our support team can help you figure out exactly what is wrong.
