### ISSUE TITLE
PHP 7.3: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"?

### ISSUE THREAD

**Issue by mattgrayisok** [braintree/braintree_php#236]
### General information

* SDK/Library version: 3.36.0
* Environment: All
* Language, language version, and OS: PHP-FPM 7.3rc5

### Issue description

Perform any action which makes use of Braintree\Util::throwGraphQLResponseException() and PHP 7.3 will throw an exception with the message `"continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"?`

Suggest we replace `continue;` with `break;` here:

https://github.com/braintree/braintree_php/blob/master/lib/Braintree/Util.php#L102

**Comment by crookedneighbor** [comment]
Hmmmm.... the intention of that line is to continue through the loop. I wasn't aware that continue/break had special meanings in a switch statement in php. We'll have to revisit this and change these to a series of `if/else if` instead.

Thanks for the report!

**Comment by gsingh1** [comment]
+1

**Comment by pekral** [comment]
Hi, it's possible create any hotfix in soon?

**Comment by crookedneighbor** [comment]
We're gonna try to get a fix out this week.

**Comment by briandotdev** [comment]
I've submitted a PR that updates the continue statement for compatibility with PHP 7.3. Hope this can get merged quickly! #238

**Comment by crookedneighbor** [comment]
A fix for this has been released in v3.38.0 https://github.com/braintree/braintree_php/commit/0affc87b538b048514901c9865765235e5cdd9b6

**Comment by MirFidaNadeem7** [comment]
980908just open the files in a ascii editor like notepad++ by ftp goto the corresponding lines as mentioned in the error and change

continue; into continue 2;

It is really as easy as that.

**Comment by sonicist25** [comment]
> 980908just open the files in a ascii editor like notepad++ by ftp goto the corresponding lines as mentioned in the error and change
> 
> continue; into continue 2;
> 
> It is really as easy as that.

It's work!! Thanks verymuch

**Comment by sabitha-varghese** [comment]
> 980908just open the files in a ascii editor like notepad++ by ftp goto the corresponding lines as mentioned in the error and change
> 
> continue; into continue 2;
> 
> It is really as easy as that.

Great. It's work....Thank you for sharing
