### ISSUE TITLE
https issue after composer update

### ISSUE THREAD

**Issue by UMDEVELOPER** [braintree/braintree_php#237]
i have issue of
"https issue after composer update"
after add this package in laravel 5.1 i have run this command
"composer require "oureastudios/laravel5-braintree @dev " "
than my whole project css url convert from http to https

**Comment by crookedneighbor** [comment]
@UMDEVELOPER That looks like a package that wraps braintree_php, but is not maintained by Braintree. Please open an issue on the repo's page instead: https://github.com/oureastudios/laravel5-braintree
