### ISSUE TITLE
PHPUnit version not compatible with PHP 7.3

### ISSUE THREAD

**Issue by briandotdev** [braintree/braintree_php#239]
This library currently requires PHPUnit version `3.7.*`.  This version of PHPUnit is not compatible with PHP 7.3 and unit tests currently fail to run.  I had a PR all queued to to bump the PHPUnit version to 7.5 until I noticed that your integration tests require a proprietary test environment so I'm unable to verify they execute correctly under PHPUnit 7.5.

I'm happy to PR the changes I've made to migrate the unit tests to version 7.5 if you have a desire to complete the migration of integration tests.  As it stands now tests are broken under PHP 7.3.

High level changes I've made:

- Update Composer version requirements.
- Update phpunit.xml to remove obsolete syntaxCheck and enable console colors.
- Replace references to PHPUnit_Framework_TestCase with PHPUnit\Framework\TestCase.
- Moved test setup routines from _construct() to setUp().
- Replaced depreciated @expectedException and setExpectedException() with expectException().
- Added assertNull() to seven test routines that did not return a response or assert any tests.
- Added test for expected HTTP response code to HTTP test that did not make any assertions.

**Comment by briandotdev** [comment]
Thanks for the response @crookedneighbor.  Also note that PHP 7.1 has already stopped receiving security updates so it will be a big jump!  PHPUnit 6 is also ending support soon so v7 will be the way to go.  Hopefully this helps get things started.

**Comment by crookedneighbor** [comment]
This should be fixed in v4.0.0 which requires PHP 7.2.0 or higher
