### ISSUE TITLE
Descriptor name error

### ISSUE THREAD

**Issue by alexrada** [braintree/braintree_php#245]
### General information

* SDK/Library version: ## 3.35.0
* Environment: sandbox
* PHP 5.7, Ubuntu -->

### Issue description

Sending the descriptor like this, with the following examples, fail with the following error:

> Descriptor name must be 22 characters or shorter and can only contain letters and numbers.
```
...
'descriptor' => [
          'name' => ''
        ]
```

and values I tested with were:

- paymentmarand1427*
- mara*nd1427
- Mara*nd1427
- payment
- Marand1427*
- Marand1427

**Comment by hollabaq86** [comment]
To assist you in troubleshooting the issue, we're going to need some information that we prefer not be shared in a public forum like Github. Please contact [Support](https://help.braintreepayments.com/) referencing this issue and your [merchant ID](https://articles.braintreepayments.com/control-panel/important-gateway-credentials#merchant-id) for assistance.
