### ISSUE TITLE
order complete - denied

### ISSUE THREAD

**Issue by aj1322001** [braintree/braintree_php#247]
uploaded the latest 3.40.0 from the releases page, 

upon checking out, the user can enter the card details as normal, but on submission it tells the customer that the order has been placed when infact the order was denied and payment was not successful.

also, upon a denied of failed payment, the store admin will receive a notification of order placement, which is confusing if the admin doesnt look at the order status..

denied suggests the default settings, either a Gateway Rejected or Processor Declined.

i am running opencart 3.0.3.1
ssl setup, 
php 7.1

amongst that issue i also have noticed the paypal express button plugin for braintree doesn't seem to display itself and the css for the payment method interface doesn't appear to be functioning with my theme journal 3.

will report back if any other issues.
thanks!

**Comment by crookedneighbor** [comment]
It sounds to me like your issues are with opencart (which is not a Braintree product), not the underlying Braintree PHP SDK.

Please [reach out to opencart](https://www.opencart.com/) instead.

If there is a problem with the integration, you can reach out to our support team https://help.braintreepayments.com/
