### ISSUE TITLE
Transaction::sale() and how to prevent duplicated payments

### ISSUE THREAD

**Issue by TomPradat** [braintree/braintree_php#249]
### General information

* SDK/Library version: 3.39.0
* Environment: Production
* Language, language version, and OS: php 7.4

### Issue description

If I get this right it's not possible to send a unique id to prevent payments duplication. I see there is a parameter to prevent duplication in the configuration of my braintree account but the maximum is an hour.

Is there a way to prevent duplication beyond an hour ? If so how ?

**Comment by hollabaq86** [comment]
Hi @TomPradat, please [contact Support](https://help.braintreepayments.com/) who can answer your questions about preventing duplicate payments.
