### ISSUE TITLE
Please use messages in your exceptions

### ISSUE THREAD

**Issue by Danack** [braintree/braintree_php#250]
### General information

* SDK/Library version: N/A
* Environment: N/A
* Language, language version, and OS: N/A

### Issue description

Please include error messages in your exception.

Currently most of the exceptions your library throw do not include any [message in them](https://github.com/braintree/braintree_php/blob/c2729de706463e4a32e507b86712bbcb9e0815e4/lib/Braintree/Util.php#L52-L83) and people have to write custom code to convert from the exception type to what went wrong.

This makes your library harder to use, than if you included messages with the exception

**Comment by demerino** [comment]
Thanks for the feedback. We'll look into updating our error messages in the next major version. For now, any end-user facing messages should be localized by the merchant app.
