### ISSUE TITLE
What's the correct amount format?

### ISSUE THREAD

**Issue by paq85** [braintree/braintree_php#252]
### General information

* SDK/Library version: 4.0
* PHP

### Issue description

When I create a transaction I'm supposed to provide the `amount` as a `string`.
But what's the `amount` format?

In examples and tests I can see that for example for $128.55 I should send `128.55`.
1. But what's the correct format for $18,002.99? Is it `18,002.99`?
2. Should I assume that the `amount` string should be in USD currency format?
3. Should I use USD format for other currencies as well?

It would be nice to have it explained in PHP SDK doc - at least some examples for big amounts.

**Comment by crookedneighbor** [comment]
Here are the docs for amount: https://developers.braintreepayments.com/reference/request/transaction/sale/php#amount

> The billing amount of the request. This value must be greater than 0, and must match the currency format of the merchant account. Can only contain numbers and one decimal point (e.g. x.xx). Can't be greater than the maximum allowed by the processor. [Contact us](https://help.braintreepayments.com/) for your specific limit.

The `Can only contain numbers and one decimal point` bit and `must match the currency format of the merchant account` is what you're looking for.

For additional help, please reach out to our support team. https://help.braintreepayments.com/
