### ISSUE TITLE
Invalid type hints in Transaction.php

### ISSUE THREAD

**Issue by dkMorlok** [braintree/braintree_php#253]
### General information

* SDK/Library version: 4.2

### Issue description

Invalid type hints in Transaction.php in properties:
- `$creditCardDetails`  should have type `\Braintree\Transaction\CreditCardDetails`
- `$masterpassCardDetails`  should have type `\Braintree\Transaction\MasterpassCardDetails`
- `$paypalDetails` should have type `\Braintree\Transaction\PayPalDetails`
- `$localPaymentDetails` should have type `\Braintree\Transaction\LocalPaymentDetails`
- `$samsungPayCardDetails` should have type `\Braintree\Transaction\SamsungPayCardDetails`
- `$visaCheckoutCardDetails` should have type `\Braintree\VisaCheckoutCardDetails`

**Comment by cooperbarth** [comment]
Thanks for pointing this out! We'll make a note to update this. If you'd like to submit a PR, we'd be happy to take a look.

**Comment by crookedneighbor** [comment]
Opened a PR internally to fix this. Should go out in the next release.

**Comment by crookedneighbor** [comment]
This should be fixed now in the latest version. Thanks for brining it up.
