### ISSUE TITLE
Incorrect type hints for Customer Search

### ISSUE THREAD

**Issue by paul-gene** [braintree/braintree_php#258]
The type hint for the query parameter for `Customer::search()` in `lib/Braintree/Customer.php` are set to `string`, but it should be `array`

**Comment by crookedneighbor** [comment]
@paul-gene would you like to open a PR to fix it?

**Comment by paul-gene** [comment]
@crookedneighbor if only I had the time! Also, I'm actually using v3 of the SDK due to current restraints. Perhaps when we move to v4 soon, I'll see if I can find time to do a PR.
