### ISSUE TITLE
Cannot create customer with ACH payment method nonce

### ISSUE THREAD

**Issue by ghost** [braintree/braintree_php#259]
`Customer::create()` allows you to pass a nonce to create a payment method at the same time, whoever this is not true for ACH Direct Debit.

When creating the payment method on its own, you have to pass 

```
'options' => [
                'usBankAccountVerificationMethod' => 'network_check'
            ]
```

But this is not allowed in the customer create call.

Ii would be a great help if it was allowed, as it would streamline some of the logic, seeing as ACH must have a payment method created for an existing customer. Or, get rid of the requirement for a Customer ID in the payment method create call / get rid of the need to create the payment method at all.

**Comment by hollabaq86** [comment]
👋  @paul-gene, thanks for reaching out. I've forwarded your feedback to the team that owns ACH Direct Debit. This is an improvement that can be made to our API. However, it currently isn't on our roadmap, which means we don't have an ETA on when this functionality will be added.

In the meantime, I'll leave this issue open to track interest.

**Comment by paul-gene** [comment]
Excellent, thank you!

**Comment by DPoplin** [comment]
This has been forwarded onto the appropriate team. I am closing out this issue since there is no additional work on the SDK at this time.
