### ISSUE TITLE
Handling Multiple Currencies

### ISSUE THREAD

**Issue by girishkc** [braintree/braintree_php#261]
* SDK/Library version: 2.35.2
I am working on an application that accepts both USD and CAD cards. 
I am exploring 2 options:

Option 1:
Create 2 different accounts. One for USD and another for CAD

Option 2: 
Create one account with 2 merchant accounts, one with USD and another with CAD. Now 

I have to bill the card issued in Canada in CAD and all other cards in USD. 
Is there any way to get the card issued country before submitting the encrypted string to Braintree?
If not, I may have to 

- Create a customer in USD account
- Get the card issued country
- If card issued country is Canada, recreate the customer in CAD account.

Are there any better ways to handle this..?

Thanks,

**Comment by crookedneighbor** [comment]
You can use the payment method nonce find method to look up the details of the nonce: https://developers.braintreepayments.com/reference/request/payment-method-nonce/find/php

On the resulting object is a country of issuance field, which will tell you the country it was issued in if it is known: https://developers.braintreepayments.com/reference/response/payment-method-nonce/php#bin_data.country_of_issuance

Option 2 is the preferred route, I believe. Please contact our support team for help with your integration: https://help.braintreepayments.com/
