### ISSUE TITLE
Setting Proxy with AccessToken

### ISSUE THREAD

**Issue by Palochinmayee** [braintree/braintree_php#264]
### General information

* SDK/Library version: 3.40.0
* Environment: Sandbox

### Issue description

We are using access token from server calls. Along with that we need to set Proxy host and port. But unable to set that. There are some documentation I got where we can use Proxy along with other parameters in config(Public key, private key, merchant ID, environment). But How to set proxy with accesstoken ?

**Comment by hollabaq86** [comment]
👋 @Palochinmayee, can you confirm you're using an [Oauth Access Token](https://developers.braintreepayments.com/guides/extend/oauth/access-tokens/php)? Additionally, you're [creating the Braintree gateway instance](https://developers.braintreepayments.com/guides/extend/oauth/shared-vault/ruby#creating-a-shared-vault-transaction) using an access token similar to the code snippet below?

```
gateway = Braintree::Gateway.new(
  :access_token => use_access_token_for_merchant
)
```

**Comment by hollabaq86** [comment]
Wanted to add to my earlier comment, you should be able to update the `config` on your gateway instance like the following:

```
gateway->$config->proxyHost('http://your-proxy-domain.com');
gateway->$config->proxyPort('8080');
```

Let us know if this doesn't work for you!

**Comment by crookedneighbor** [comment]
This should give you everything you need to set the proxy configuration. If you're still having trouble, contact our support team. https://help.braintreepayments.com/
