### ISSUE TITLE
ErrorTokenizing while checkout in sandbox.

### ISSUE THREAD

**Issue by AryanBurman** [braintree/braintree_php#266]
![WhatsApp Image 2020-01-28 at 18 45 14](https://user-images.githubusercontent.com/53735548/73328326-5b675580-427f-11ea-953d-1243e7aa0df0.jpeg)

**Comment by scannillo** [comment]
Hi @AryanBurman, this error is coming from `braintree-web` https://github.com/braintree/braintree-web/blob/a99f2ee3d7a56f4392bbe74e8ccb722d413cbe14/src/paypal-checkout/errors.js#L52-L56. 

Also, we don't have enough information, which SDK you're on, what your integration looks like, or steps to reproduce your issue. 

To troubleshoot your integration, reach out to https://help.braintreepayments.com/.
