### ISSUE TITLE
Feature request: set properties on webhookTesting()->sampleNotification()

### ISSUE THREAD

**Issue by steffenbrand** [braintree/braintree_php#274]
### General information

* SDK/Library version: 5.0.0
* Environment: sandbox
* Language, language version, and OS: php 7.2 on Linux Mint 19

### Issue description

I really like the `webhookTesting` feature of your php-sdk.
But currently I'm only able to set the ID of the "additional attribute".
In my case a `subscription`.

```
$gateway = new Gateway([
    'merchantId' => $_ENV['BRAINTREE_MERCHANT_ID'],
    'environment' => $_ENV['BRAINTREE_ENVIRONMENT'],
    'publicKey' => $_ENV['BRAINTREE_API_PUBLIC_KEY'],
    'privateKey' => $_ENV['BRAINTREE_API_PRIVATE_KEY']
]);

$sampleNotification = $gateway->webhookTesting()->sampleNotification(
    WebhookNotification::SUBSCRIPTION_CANCELED,
    'unknownSubscriptionId'
);
```

I would really like to be able to set all properties, so I can simulate all states.
I would allow me to use the sdk even for integration testing.
Maybe it could look like this:

```
$gateway = new Gateway([
    'merchantId' => $_ENV['BRAINTREE_MERCHANT_ID'],
    'environment' => $_ENV['BRAINTREE_ENVIRONMENT'],
    'publicKey' => $_ENV['BRAINTREE_API_PUBLIC_KEY'],
    'privateKey' => $_ENV['BRAINTREE_API_PRIVATE_KEY']
]);

$sampleNotification = $gateway->webhookTesting()->sampleNotification(
    WebhookNotification::SUBSCRIPTION_CANCELED,
    [
        'id' => 'mySubscriptionId',
        'status' => \Braintree\Subscription::CANCELED,
        'updatedAt' => new \DateTimeImmutable()
    ]
);
```

**Comment by hollabaq86** [comment]
👋 @steffenbrand thanks for the request! We've had similar requests in some of our other server SDKs, and we're brainstorming solutions. 

I don't have an ETA on when this would be added to the SDK, but in the meantime, I'm going to leave this issue open to track interest.

**Comment by Surf-N-Code** [comment]
+1

**Comment by mkraemer** [comment]
+1 :)

**Comment by xyNNN** [comment]
+1

**Comment by acfo** [comment]
+1

**Comment by DPoplin** [comment]
This issue has been forwarded to the engineering team that owns our webhooks platform. I'm going to close this issue as no additional work will take place within the SDK at this time.
