### ISSUE TITLE
XML Generator DateTimeImmutable support

### ISSUE THREAD

**Issue by mprokocki** [braintree/braintree_php#278]
### General information

* SDK/Library version: 5.2.0
* Environment: NONE
* Language, language version, and OS: PHP 7.4.7  | Ubuntu 20.04

### Issue description

`Braintree\Xml\Generator::_createElementsFromArray` line 89 throwing exception when one of attributes e.g. `firstBillingDate` in subscription gateway is `DateTimeImmutable` instance.

**Comment by hollabaq86** [comment]
👋 @mprokocki thanks for reaching out. `firstBillingDate` [should be](https://github.com/braintree/braintree_php/blob/c82b5297c617b4ad37b1d16edc8aa869d1f47047/lib/Braintree/Subscription.php#L25) `DateTime` [class](https://developers.braintreepayments.com/reference/request/subscription/create/php#first_billing_date), do you encounter the same issue if you set `firstBillingDate` to a `DateTime` class?

**Comment by mprokocki** [comment]
If `firstBillingDate` is `DateTime` class everything is alright, just wondering why you are not supporting `DateTimeImmutable` also??

**Comment by crookedneighbor** [comment]
@mprokocki if you'd like to open a PR, we'd be happy to review it. Will just need to make sure it does not cause any breaking changes (or it'll have to wait till the next major version bump)

**Comment by hollabaq86** [comment]
👋  Version 6.0.0 includes updates to support the `DateTimeImmutable` class 🎉  I'm going to go ahead and close this issue, but please let us know if you continue to encounter problems around these changes.
