### ISSUE TITLE
Feature Request: Custom HTTP client

### ISSUE THREAD

**Issue by patrickkusebauch** [braintree/braintree_php#281]
### General information

* SDK/Library version: 5.3.0
* Environment: Sandbox
* Language, language version, and OS: PHP7.4.0 on Dockerized php:7-fpm

#### Setup
Currently, we are forced into using the included HTTP client implementation. Example from `SubscriptionGateway` class

```php
class SubscriptionGateway
{
    private $_gateway;
    private $_config;
    private $_http;

    public function __construct($gateway)
    {
        $this->_gateway = $gateway;
        $this->_config = $gateway->config;
        $this->_config->assertHasAccessTokenOrKeys();
        $this->_http = new Http($gateway->config);
    }
}
```

This HTTP class cannot be switched, since it is created directly in the class and not passed as a dependency.

This `HTTP` class, in turn, creates `CurlRequest` class that is again hardcoded and cannot be swapped by any means:

```php
class Http
{
    public function _doUrlRequest($httpVerb, $url, $requestBody = null, $file = null, $customHeaders = null)
    {
        $curlRequest = new CurlRequest($url);
        return Curl::makeRequest($httpVerb, $url, $this->_config, $curlRequest, $requestBody, $file, $customHeaders, $this->_useClientCredentials);
    }
}
```
This `CurlRequest` class calls `curl_*` methods directly and therefore there is no way to alter/add any further code.

#### Why change?
Because right now there is no possibility for any type of logging, analytics, and metrics for the requests.
I cannot track any information about the CURL requests themselves, at best, I can wrap the library code itself, but that gives me only very little information in contrast to what `curl_getinfo` can give you about the request.

**Comment by hollabaq86** [comment]
👋 @patrickkusebauch thanks for reaching out. We've talked this over internally, and we're going to pass on this request - it introduces a support burden that we're not willing to take on, plus folks can continue to use responses as they are for logging/analytics of requests.

This said, you're 💯  welcome to fork our repo and make the changes you need.

**Comment by AidasK** [comment]
Hello @patrickkusebauch, have you found a solution to overcome this?

**Comment by AidasK** [comment]
Same issue: https://github.com/braintree/braintree_php/issues/141

**Comment by mcsocha** [comment]
My team has a need for a custom HTTP client. Wondering if anyone can reconsider?
