### ISSUE TITLE
PayPal Express Checkout via Braintree SDK Live account not working since 2020-09-17

### ISSUE THREAD

**Issue by martincz** [braintree/braintree_php#283]
# General information
* SDK/Library version: 3.40.0
* Environment: Production

### Issue description
I didn't do anything.
Braintree sdk response code return 2046, Declined.
When I switch to use sandbox access token, it work fine.
Can you help me?

**Comment by crookedneighbor** [comment]
Reach out to our support team so we can investigate your account: https://help.braintreepayments.com/
