### ISSUE TITLE
Feature request: generate client token with expiration date

### ISSUE THREAD

**Issue by ganboonhong** [braintree/braintree_php#284]
### General information

* SDK/Library version: 5.3.0
* Environment: Sandbox
* Language, language version, and OS: PHP 7.3.21 on Amazon Linux 2

### Issue description

When generating client token, Is it possible to pass an expiration date (absolute/relative time) as parameter to let the token to expire in desired time?

https://github.com/braintree/braintree_php/blob/b5e971d898c78819cf2fddab7043b7c7c69e841e/lib/Braintree/ClientTokenGateway.php#L38-L48

Currently, client tokens are valid for up to 24 hours according to the document.

https://developers.braintreepayments.com/guides/authorization/client-token

Use case:
I'm implementing [PayPal checkout](https://developers.braintreepayments.com/guides/paypal/server-side/php#creating-transactions). When users clicked the yellow PayPal button, a new pop-up window will come out. If users leave the window open and come back an hour later, they can still pay successfully which I don't want it to happen. 

So, is it possible to prevent it from happening by specifying a shorter expiration date on the client token?

![Screen Shot 2020-10-22 at 10 38 54 AM](https://user-images.githubusercontent.com/10766871/96818290-c5e6a400-1453-11eb-9bd7-9d0fc16f48d9.png)

**Comment by crookedneighbor** [comment]
No. You'll have to implement a client side check to timeout after inactivity and [reload your page to remove the connection to PayPal](https://developer.paypal.com/docs/archive/express-checkout/digital-goods/ClosingWindow/#reload-parent-page-to-a-specific-url).
