### ISSUE TITLE
@property-read documentation for Transaction incorrectly documents addons instead of addOns.

### ISSUE THREAD

**Issue by brianium** [braintree/braintree_php#285]
### General information

* SDK/Library version: braintree/braintree_php:5.4.0
* Environment: Affects all environments
* Language, language version, and OS: PHP 7.4, but should affect all supported versions. 

### Issue description

The `@property-read` documentation for Transaction incorrectly documents `addons` instead of `addOns`. While not a severe issue, it does break static analysis tools.

Line in question:
https://github.com/braintree/braintree_php/blob/master/lib/Braintree/Transaction.php#L144

**Comment by crookedneighbor** [comment]
Thanks! Would you like to open a PR to fix the documentation?

**Comment by brianium** [comment]
Sure thing. Incoming!

**Comment by brianium** [comment]
@crookedneighbor PR submitted 🙇 

Let me know if anything else is required.

Thank you!

**Comment by crookedneighbor** [comment]
:+1: Thanks
