### ISSUE TITLE
"Create a transaction with an authentication ID" PHP documentation incorrect

### ISSUE THREAD

**Issue by ChrisHSandN** [braintree/braintree_php#287]
### General information

* SDK/Library version:  Latest
* Environment:  Documentation
* Language, language version, and OS:  PHP

### Issue description

The documentation for PHP (and all languages apart from ruby) is wrong in the section "Create a transaction with an authentication ID"
https://developers.braintreepayments.com/guides/3d-secure/server-side/php#create-a-transaction-with-an-authentication-id

Note how the PHP example doesn't reference the same variables as the ruby example. Looks like it was copied from "Create a transaction using a 3D Secure upgraded nonce".

***

### The PHP example code:
![image](https://user-images.githubusercontent.com/13466620/101892321-23b58380-3b9b-11eb-919c-2ccaa77de444.png)

*** 

### The ruby example code:
![image](https://user-images.githubusercontent.com/13466620/101892355-2fa14580-3b9b-11eb-926f-1fb1864b9da5.png)

**Comment by ChrisHSandN** [comment]
Another issue:

https://developers.braintreepayments.com/guides/3d-secure/testing-go-live/php

Has `**` next to each expiry date but no where on the page mentions the vital information that it means you have to use "use the current year +3"

This is documented only on this page in the red boxout (but still doesn't actually reference that it relates to the `**`):
https://developers.braintreepayments.com/guides/3d-secure/migration/javascript/v3#client-side-sandbox-testing

**Comment by hollabaq86** [comment]
👋 @ChrisHSandN thanks for reaching out. At the bottom of each of these pages in our docs is a button `Send Feedback`. Please use that feedback form going forward so this information gets to the right team. I'm going to forward this feedback for you and close this issue.

**Comment by ChrisHSandN** [comment]
If I am honest the:
> Give us feedback on this page
> Submit this short survey to let us know how we can improve your experience.

Made it sound like it would go to a marketing survey department rather than anyone who understood the API...

I shall use that link in future 😊

**Comment by crookedneighbor** [comment]
Survey is probably not the best choice of words there, I'll pass that on to our docs team. Thanks for the feedback!
