### ISSUE TITLE
Testing 3ds subscriptions with fake nonces

### ISSUE THREAD

**Issue by brandonburkett** [braintree/braintree_php#288]
### General information

* SDK/Library version: 5.4.0
* Environment: Sandbox
* Language, language version, and OS: PHP .3

### Issue description

We are adding 3ds support for both transactions and subscriptions and testing in sandbox.  Transactions seem to work fine with any of the test nonces here: https://developers.braintreepayments.com/reference/general/testing/php#nonces-representing-cards

But for subscriptions, when we need to pass in the 3ds enriched nonce directly to `subscription()->create`, both `fake-valid-nonce` and `fake-three-d-secure-visa-full-authentication-nonce` are failing with the following error:

```
Error: 91925: Payment method nonce is invalid.
```

How can we test 3ds subscriptions with fake nonces?

Thanks,
Brandon

**Comment by hollabaq86** [comment]
👋  please [contact Support](https://help.braintreepayments.com/) for assistance integrating 3DS.
