### ISSUE TITLE
Auth error when trying to make a transaction

### ISSUE THREAD

**Issue by JohnWeeks1** [braintree/braintree_php#291]
When adding the basic example code to my Laravel project I keep getting this error

![image](https://user-images.githubusercontent.com/17055567/111815987-32b37c80-88d4-11eb-9937-2ce1b6605a8f.png)

I'm generating the auth token on the server-side, sending it to the client and all the fields are working. When trying to execute a transaction()->sale() on the server-side I get the above error 

```php
$gateway = new Braintree\Gateway([
    'environment' => config('services.braintree.environment'),
    'merchantId'  => config('services.braintree.merchantId'),
    'publicKey'   => config('services.braintree.publicKey'),
    'privateKey'  => config('services.braintree.privateKey')
]);

$result = $gateway->transaction()->sale([
    'amount' => '5.99',
    'paymentMethodNonce' => $request->get('nonce'),
  ]);
```

The credentials are also correct because I can create a customer but not a transaction

Thanks

**Comment by crookedneighbor** [comment]
Your API user probably doesn't have the permissions set to create a transaction. Reach out to our support team for help with this. https://help.braintreepayments.com/
