### ISSUE TITLE
invalid keys: lineItems[imageUrl]

### ISSUE THREAD

**Issue by EvilLooney** [braintree/braintree_php#293]
### General information

* SDK/Library version: 5.5.0
* Environment: Sandbox
* Language, language version, and OS: PHP 7.2 Ubuntu 20.04

### Issue description

Hello,

Based on your documentation, it says we can add a product image url for line items:
[https://developers.braintreepayments.com/reference/request/transaction/sale/php#line_items.image_url](url)

But doing so throws an `InvalidArgumentException`.

I looked at the code and cannot find a reference to that key.

So my question is, is this an error in the docs or an error in the code base?

Thanks.

**Comment by hollabaq86** [comment]
👋  Thanks for reaching out, looks like the docs got updated before [the SDK](https://github.com/braintree/braintree_php/blob/e22dc11e5e92182999288d914d14640a3f50cd85/lib/Braintree/TransactionGateway.php#L256), sorry about that. Want to PR it?

**Comment by EvilLooney** [comment]
Hi Holly,

I literally just installed the package this morning. So no, I am not comfortable doing a PR at this time.

Sorry!

**Comment by hollabaq86** [comment]
@EvilLooney no worries! We'll get this added to the SDK 😄

**Comment by hollabaq86** [comment]
this was actually a mistake in the docs, and is now removed. Apologies for the delay and confusion
