### ISSUE TITLE
> [](https://developers.braintreepayments.com/reference/general/validation-errors/all/ruby#code-93107)Имена постојаних [кодова грешака](https://developers.braintreepayments.com/reference/general/validation-errors/all/ruby#code-93107) 93106 и 93107 се преокрећу.

### ISSUE THREAD

**Issue by Body87** [braintree/braintree_php#296]
> [](https://developers.braintreepayments.com/reference/general/validation-errors/all/ruby#code-93107)Имена постојаних [кодова грешака](https://developers.braintreepayments.com/reference/general/validation-errors/all/ruby#code-93107) 93106 и 93107 се преокрећу.
> 
> https://github.com/braintree/braintree_ruby/blob/fa974389eddb9f5b8f414f88e226f4868b4921e7/lib/braintree/error_codes.rb#L712
> 
> https://github.com/braintree/braintree_ruby/blob/fa974389eddb9f5b8f414f88e226f4868b4921e7/lib/braintree/error_codes.rb#L706
> 
> ПаиментМетходНонцеЦонсумед треба да буде 93107
> ЦаннотФорвардПаиментМетходТипе треба да буде 93106

_Originally posted by @Body87 in https://github.com/braintree/braintree_ruby/issues/213#issuecomment-841800493_

**Comment by scannillo** [comment]
👋  Hello. This change is being addressed in braintree_ruby issue #213.
