### ISSUE TITLE
How to pay with different currency?

### ISSUE THREAD

**Issue by WeTruck** [braintree/braintree_php#298]
I'm following this link: https://developers.braintreepayments.com/start/hello-server/php#create-a-transaction

```
$result = $gateway->transaction()->sale([
  'amount' => '10.00',
  'paymentMethodNonce' => $nonceFromTheClient,
  'deviceData' => $deviceDataFromTheClient,
  'options' => [
    'submitForSettlement' => True
  ]
]);
```

It's working properly. But paying always in USD. 
How can I pay from different currency? 
Like is there any object for currency? As `'currency' => 'EUR'`

Looking for help. Thanks in advance.

**Comment by sestevens** [comment]
Hi @WeTruck, the currency is determined by your merchant account ID. We explain this a bit more in the [developer docs](https://developers.braintreepayments.com/reference/request/transaction/sale/php#merchant_account_id).

**Comment by WeTruck** [comment]
Thanks @sestevens 
How can I change my merchant account currency then? I'm on sandbox mode.

**Comment by sestevens** [comment]
Here's a link with instructions: https://articles.braintreepayments.com/get-started/try-it-out#testing-currencies.

**Comment by crookedneighbor** [comment]
For additional help with this, please reach out to our support team: https://help.braintreepayments.com/

**Comment by WeTruck** [comment]
Thanks @sestevens @crookedneighbor
