### ISSUE TITLE
Fatal error with PHP8 and v3

### ISSUE THREAD

**Issue by ziemkowski** [braintree/braintree_php#299]
### General information

* SDK/Library version: 3.40.0
* Environment: Production
* Language, language version, and OS: PHP8

### Issue description

The latest v3 release has a fatal error in php8:

```
PHP Fatal error:  Array and string offset access syntax with curly braces is no longer supported
in composer/braintree/braintree_php/lib/Braintree/Digest.php on line 53
```

**Comment by crookedneighbor** [comment]
:wave: v6.x is the actively maintained version of this SDK. Does the same issue happen when running PHP 8 against v6 of the SDK?

**Comment by ziemkowski** [comment]
@crookedneighbor Thanks for the quick response. We're not in a position to be able to refactor our usage, since v4 on introduced a significantly different design pattern. 

I wouldn't have submitted the issue, but the readme says [v3 is still supported](https://github.com/braintree/braintree_php#versions), so figured I would.

**Comment by scannillo** [comment]
👋 Hello - our [Deprecation Policy](https://developers.braintreepayments.com/reference/general/server-sdk-deprecation-policy) defines an "Inactive" SDK as one where "No new features will be added, only security updates."

 Since this is not a security issue, and our "active" SDK version offers official support for PHP 8+, we encourage you to update to v6.x of our PHP SDK if you want to use PHP 8.

**Comment by ziemkowski** [comment]
Do you know if there is a migration guide still available for v4?  I thought that the upgrade path from v3 was heavier than the v5/v6 [migration guide](https://developers.braintreepayments.com/reference/general/server-sdk-migration-guide/php) suggests.

**Comment by crookedneighbor** [comment]
Looking at the v4 changelog, most of the breaking changes were removing classes for APIs that are no longer in use: https://github.com/braintree/braintree_php/blob/master/CHANGELOG.md#400

The only other potentially breaking changes I see are the removal of some snake case properties in favor of camel case properties:

> Remove `riskData`, `applePay`, `applePayCard`, `threeDSecure`, and `venmo.profileId` snakecase attributes

And renaming `DownForMaintance` error to `ServiceUnavailable`
