### ISSUE TITLE
Wrong phpdoc return types in several classes

### ISSUE THREAD

**Issue by Meyfarth** [braintree/braintree_php#314]
### General information

* SDK/Library version: 6.7.0
* Environment: Sandbox
* Language, language version, and OS: PHP 8.1

### Issue description

After updating to the latest version of braintree_php, our static analysis tool didn't recognize the magic properties anymore (I saw in-between that `@property` annotations were removed, that would explain it).

I tried to bypass this by calling the `__get()` method (which is defined in the base class) directly, but then ended up having another error: can't call `__get()` on unknown class `\Braintree\Error`

The PHPDoc regarding this return type on few classes are not up to date. I already created a PR with the fix (#313), including each class that had a faulty PHPDoc.

Please feel free to close this when you merge the PR

**Comment by hollabaq86** [comment]
👋  @Meyfarth thanks for reaching out, going to close this issue so that we can track all type fixes in one pinned issue (#305)
