### ISSUE TITLE
Passing Item lines to PayPal?

### ISSUE THREAD

**Issue by ClubPlug** [braintree/braintree_php#318]
### General information

* SDK/Library version: 
* Environment: 
* Language, language version, and OS: 

### Issue description

Hi
Was wondering if there is any way of passing a carts items lines when the customers chooses to pay with PayPal.
At the moment, only the Total amount is passed.  All the Cart Items are NOT passed.

Thanks
FV

**Comment by hollabaq86** [comment]
👋  @ClubPlug thanks for reaching out. I'm going to forward this feedback to the team that owns paying with PayPal. I don't have an ETA on if or when this would get added, but the feedback has been sent!
