### ISSUE TITLE
bad link to documentation

### ISSUE THREAD

**Issue by columbian-chris** [braintree/braintree_php#319]
When I follow the link to https://developers.braintreepayments.com/php/sdk/server/overview, it gives me a blank page.  Is there a new home for these docs somewhere?

**Comment by crookedneighbor** [comment]
I believe the correct link is: https://developer.paypal.com/braintree/docs/start/hello-server/php

**Comment by crookedneighbor** [comment]
Actually, it's https://developer.paypal.com/braintree/docs/start/overview for the overview.

**Comment by columbian-chris** [comment]
Thanks, Blade.  I would appreciate it if this could be updated in the github repo settings.

**Comment by crookedneighbor** [comment]
I don't actually see that link anywhere in this repo. Can you point to where you see that link? I'm sure it's right in front of me and I just can't see it.

**Comment by columbian-chris** [comment]
If you look on the [main repo page](https://github.com/braintree/braintree_php) on the right hand side:

<img width="325" alt="Screen Shot 2022-04-22 at 2 40 47 PM" src="https://user-images.githubusercontent.com/24399987/164799634-66af777d-b95c-47a1-b6f3-e8cf3b7fa58b.png">

**Comment by crookedneighbor** [comment]
Awesome, I was looking in the README and the code itself. No wonder I missed it! It's now fixed. I'm going to go through the other server sdks and fix it there too. Thanks again for pointing it out!
