### ISSUE TITLE
lib/Braintree/GraphQLClient: php 8.2 deprecation warning due to missing property

### ISSUE THREAD

**Issue by mvoelker** [braintree/braintree_php#324]
### General information

* SDK/Library version: 6.10.0
* Environment: Production
* Language, language version, and OS: php 8.2.0 von Windows 11

### Issue description

Generated warning:
```Deprecated: Creation of dynamic property Braintree\GraphQLClient::$_service is deprecated in [...]/vendor/braintree/braintree_php/lib/Braintree/GraphQLClient.php on line 14```

### Solution

Add this line to the top of the class body ```/lib/Braintree/GraphQLClient.php```:

```
...
    /**
     * @var GraphQL|null
     */
    protected $_service = null;
...
```

**Comment by DPoplin** [comment]
Hey @mvoelker thanks for reporting this! We will be taking a look at this and following up with any additional questions as they arise. 

For internal reference: DTBTSDK-2159
