### ISSUE TITLE
Missing updateTransactionCustomFields mutation

### ISSUE THREAD

**Issue by bserprixwq** [braintree/braintree_php#328]
### General information

* SDK/Library version: 6.11.2
* Environment: sandbox
* Language : PHP 7.3

### Issue description

It seems that the GraphQL mutation [`updateTransactionCustomFields`](https://graphql.braintreepayments.com/reference/#Mutation--updateTransactionCustomFields) is not implemented

It would be really useful !

**Comment by hollabaq86** [comment]
👋 @bserprixwq thanks for reaching out! We've forwarded your request for evaluation and potential prioritization. We can't provide an ETA on if/when this would get added to the library. But in the meantime, if you'd like to submit a PR for your idea you are welcome to do so!

If anyone would love to see this added to the SDKs, feel free to add a 👍 to the issue so we can gauge interest.

For internal tracking, ticket 2069
