### ISSUE TITLE
gnutls_handshake() failed: Error in the pull function.

### ISSUE THREAD

**Issue by pumpernikiell** [braintree/braintree_php#330]
### General information

* SDK/Library version: 6.9.0
* Environment: Production
* Language, language version, and OS: PHP 8.2.2 on Ubuntu 18.04.6 LTS, 
    "ssl_version": "GnuTLS\/3.5.18",
    "libz_version": "1.2.11",

### Issue description

Sometimes an error occurs while generating token using ClientToken::generate()

![image](https://github.com/braintree/braintree_php/assets/57671841/d6598f7b-a98b-40d2-abac-d132c3e036ae)

**Comment by hollabaq86** [comment]
👋 @pumpernikiell, thanks for reaching out. We throw that exception when we receive [CURLE_SSL_CONNECT_ERROR](https://curl.se/libcurl/c/libcurl-errors.html)s (errorCode 35), Support is going to need more information to dig in further.

Can you [contact Support](https://developer.paypal.com/braintree/help) referencing this issue, along with the following information:

- when did these errors start appearing?
- have you made any recent updates to your integration shortly before these errors started appearing?
- this is only happening when trying to generate a client token? No other API calls?
- timestamps or errors, or how frequently it's happening (once a day? once a week?)
- **timestamps of failed calls**, especially, would be helpful.
- **IP addresses** of your server that experienced these failed requests
