### ISSUE TITLE
Testing network failure causes SSL exception

### ISSUE THREAD

**Issue by zombor** [braintree/braintree_php#5]
I'm trying to test cases where the braintree gateway is unavailable (host down, dns failure, etc), and I get a Braintree_Exception_SSLCertificate exception because of:

https://github.com/braintree/braintree_php/blob/master/lib/Braintree/Http.php#L94

It seems like it should be testing if $result is empty, and throw a different kind of exception.

**Comment by kbdavis07** [comment]
I am getting this error with WHMCS.

modules\gateways\braintree\lib\Braintree\Http.php:94

Had this been fixed?

**Comment by gigo6000** [comment]
I had this same issue, in my case it was a DNS issue on my vagrant VM, but I had to debug it printing the $error_code variable, that is assigned on line 149:

```
149         $error_code = curl_errno($curl);
150 
151         if ($error_code == 28 && $httpStatus == 0) {
152             throw new Exception\Timeout();
153         }
154 
155         curl_close($curl);
156         if ($this->_config->sslOn()) {
157             if ($httpStatus == 0) {
158                 throw new Exception\SSLCertificate();
159             }
160         }
161         return ['status' => $httpStatus, 'body' => $response];

```

```
149         $error_code = curl_errno($curl);
150 
151 echo $error_code;exit;
152         if ($error_code == 28 && $httpStatus == 0) {
153             throw new Exception\Timeout();
154         }
```

I got 6 as the error number :

CURLE_COULDNT_RESOLVE_HOST (6)
Couldn't resolve host. The given remote host was not resolved.
