### ISSUE TITLE
Payment Method Update Issue

### ISSUE THREAD

**Issue by wtbloom** [braintree/braintree_php#50]
I'm getting the error message "Payment Method nonces cannot be used to update an existing card" when trying to use Braintree_PaymentMethod::update.  This seems to be the opposite of the what documentation says.

**Comment by TylerScottSullivan** [comment]
Hello, I am dealing with this same issue. Could it have been broken again?

**Comment by openbl** [comment]
@TylerScottSullivan, if you're having this issue, it is most likely something specific to your integration. Our technical support team is the best to help you work through this. Feel free to email (support@braintreepayments.com) or call (877.434.2894).

**Comment by mairo744** [comment]
+1 work in sandbox with fake nonces but not with real nonces.

**Comment by crookedneighbor** [comment]
@mairo744 please reach out to our technical support team to figure out what is going wrong: https://developer.paypal.com/braintree/help
