### ISSUE TITLE
"no matching public key" error when trying to generate sample webhook notification

### ISSUE THREAD

**Issue by borfast** [braintree/braintree_php#52]
When I use the code from https://developers.braintreepayments.com/javascript+php/sdk/server/webhooks/testing to try to generate a sample webhook notification, so I can understand what I'll be getting back from the server, I only get an error saying "no matching public key".

I am using the exact code from the aforementioned page, so I don't think I'm missing anything, but alas, it doesn't work.

Can anyone point me in the right direction, please?

**Comment by Ewg777** [comment]
@borfast how did you solve this issue?

**Comment by borfast** [comment]
@Ewg777, like I said before, I didn't do anything. It suddenly just started working. I have no idea what it was.

**Comment by ibekiaris** [comment]
The problem is that you did not configure braintree before generate sample notification.

Braintree_Configuration::environment('sandbox');
Braintree_Configuration::merchantId('use_your_merchant_id');
Braintree_Configuration::publicKey('use_your_public_key');
Braintree_Configuration::privateKey('use_your_private_key');

**Comment by borfast** [comment]
No, the configuration code was correct. Besides, if it wasn't correct, it wouldn't have worked.

**Comment by ibekiaris** [comment]
The config may was correct but not took place before sample data generation. May be you configured Braintree in a wrong place... May be you moved (I am not saying you changed your code) your config or your sample generation code an it worked.

**Comment by borfast** [comment]
Maybe, I don't know, it was a long time ago.

**Comment by Ewg777** [comment]
@ibekiaris contact to braintree technical support.

**Comment by itsykhovskyi** [comment]
I had the same problem. So i discribe it. _Braintree_WebhookNotificationGateway_ class is using static method of _Braintree_Configuration_ class for retrieving credentials. And this static method retrieve data only from static _$global_ propery. And _Braintree_Gateway_ constructor doesn't set data into it like another gateway classes

1 option. (not working, "no matching public key" appears)
$gateway = new Braintree_Gateway([
            'environment' => 'sandbox'
            'merchantId' =>'use_your_merchant_id',
            'publicKey' => 'use_your_public_key',
            'privateKey' => 'use_your_private_key',
        ])
$gateway->webhookNotification()->parse(...)

2 option. (working)
Braintree_Configuration::environment('sandbox');
Braintree_Configuration::merchantId(('use_your_merchant_id');
Braintree_Configuration::publicKey('use_your_public_key');
Braintree_Configuration::privateKey('use_your_private_key');
$gateway = new Braintree_Gateway(Braintree_Configuration::$global);
$gateway->webhookNotification()->parse(...)

**Comment by sabin-stw** [comment]
[
![braintree](https://user-images.githubusercontent.com/59480366/125657025-0581025a-90f3-4257-9124-75235c20a120.JPG)
](url)

can anyone help me with this please

**Comment by crookedneighbor** [comment]
@sabin-stw reach out to our support team for assistance https://developer.paypal.com/braintree/help

**Comment by sabin-stw** [comment]
@crookedneighbor Thank you for your suggestion.

**Comment by kanikbenzeen** [comment]
@sabin-stw i'm having the same issue just want to know if you find some solution for this or not

**Comment by kanikbenzeen** [comment]
> @sabin-stw reach out to our support team for assistance https://developer.paypal.com/braintree/help



> @sabin-stw reach out to our support team for assistance https://developer.paypal.com/braintree/help

Please tell me its solution if you found out

**Comment by shivm29** [comment]
Are you using process.env ??
