### ISSUE TITLE
create_function should be replaced by anonymous function

### ISSUE THREAD

**Issue by jhammer** [braintree/braintree_php#55]
There are currently two uses of the "create_function" in the PHP SDK codebase. They can both be easily replaced with anonymous functions (closures). This would be a great win because:

1. HHVM does not support the create_function function. Currently the PHP SDK cannot be used under HHVM because of this.

2. PHP's own documentation advises against use of create_function: "Caution
This function internally performs an eval() and as such has the same security issues as eval(). Additionally it has bad performance and memory usage characteristics."

Thanks!

**Comment by matthewpatterson** [comment]
Cannot reproduce under HHVM 3.7.0. If you find that you have this issue, please feel free to re-open.
