### ISSUE TITLE
Braintree_Xml_Generator::_createElementsFromArray being called with too many arguments

### ISSUE THREAD

**Issue by jhammer** [braintree/braintree_php#56]
Braintree_Xml_Generator::_createElementsFromArray takes two arguments but it is being called with three from Braintree_Xml_Generator::arrayToXml (line 38)

This doesn't cause problems when executing under the PHP interpreter, but it screws up XML generation when running under HHVM

**Comment by matthewpatterson** [comment]
Cannot reproduce under HHVM 3.7.0. If you find that you have this issue, please feel free to re-open.
