### ISSUE TITLE
Braintree_Xml_Generator::_createElementsFromArray should not take $writer by reference

### ISSUE THREAD

**Issue by jhammer** [braintree/braintree_php#57]
Currently:

    private static function _createElementsFromArray(&$writer, $aData)

Should be:

    private static function _createElementsFromArray($writer, $aData)

When executing under PHP interpreter, it works fine, but breaks when executing under HHVM

**Comment by matthewpatterson** [comment]
Hey @jhammer, are you still seeing this? If so, could you provide some more information about which version of HHVM you're running and how you're getting to the error? I'm working on getting this library working with HHVM, and at least on HHVM 3.7.0 this does not seem to be breaking.

**Comment by jhammer** [comment]
This was happening on whatever HHVM was current back in Sep 2014. We reverted back to PHP 5.4 (instead of HHVM) for all the Braintree-related code so, unfortunately, I can't give you any more detail at the moment. I don't anticipate having the bandwidth to look into this any time soon. Sorry about that. Feel free to close the issue and I'll re-open if it crops up again.

**Comment by matthewpatterson** [comment]
I'm going to go ahead and close this then, as well as #55 and #56. If you do find that something isn't working right, definitely feel free to re-open. Thanks again!
