### ISSUE TITLE
UTC not a valid timezone in CentOS 6.6

### ISSUE THREAD

**Issue by DnSu** [braintree/braintree_php#65]
/braintree-php-2.35.2/lib/Braintree/TransparentRedirectGateway.php Line 239
```$now = new DateTime('now', new DateTimeZone('UTC'));```

Causes exception to be thrown:
PHP Fatal error:  Uncaught exception 'Exception' with message 'DateTimeZone::__construct(): Unknown or bad timezone (UTC)'

Any of the following would work:
```$now = new DateTime('now', new DateTimeZone('Etc/UTC'));```
```$now = new DateTime('now', new DateTimeZone('GMT0'));```

Only observed on CentOS 6.6

**Comment by dewyze** [comment]
Hello @DnSu, I work at Braintree and did not have a problem with this on CentOS. I have found two possible solutions:

The timezone info that ships with php is in `tzdata`. Is `UTC` available in `/usr/share/zoneinfo/`? It was available on my system, but it was a fresh install of CentOS 6.6. If not, you can try updating your tzdata and see if that resolves the problem. The command `yum update tzdata` should work.

Another solution is to follow these [instructions](http://www.amitnepal.com/installing-php-time-zone-database/) to install the timezonedb extension via PECL.

**Comment by DnSu** [comment]
you are correct. I was able to spin up another instance to confirm, UTC seems to be working in the fresh instance.

**Comment by dewyze** [comment]
Glad to hear you got everything worked out!
