### ISSUE TITLE
PaymentMethod::Create() does not take raw credit card fields

### ISSUE THREAD

**Issue by kevinkyao** [braintree/braintree_php#67]
According to the docs, the PaymentMethod::Create() API call should support taking raw credit card fields (number, cvv, etc.)
https://developers.braintreepayments.com/javascript+php/reference/request/payment-method/create

However, the PHP SDK doesn't actually allow it:
https://github.com/braintree/braintree_php/blob/master/lib/Braintree/PaymentMethodGateway.php#L102

```php
 private static function baseSignature($options)
{
$billingAddressSignature = Braintree_AddressGateway::createSignature();
return array(
'customerId',
'paymentMethodNonce',
'token',
'billingAddressId',
'deviceData',
array('options' => $options),
array('billingAddress' => $billingAddressSignature)
);
}
public static function createSignature()
{
$options = array(
'makeDefault',
'verifyCard',
'failOnDuplicatePaymentMethod',
'verificationMerchantAccountId'
);
$signature = self::baseSignature($options);
return $signature;
}
```

**Comment by openbl** [comment]
`PaymentMethod::Create()`'s argument is actually an associative array of parameters for the `Braintree_Address` as shown in the docs link you mentioned. The `baseSignature()` method is an internal, faux-private method that is used in validating the associative array passed into the `Create()` method. The array returned from `baseSignature()` maps to the allowable keys within the associative array to `PaymentMethod::Create()`.

**Comment by kevinkyao** [comment]
I agree with your statements, but I don't believe it addresses my original point.

The allowable fields returned from PaymentMethodGateway::baseSignature() are:
customerId',
'paymentMethodNonce',
'token',
'billingAddressId',
'deviceData',
array('options' => $options),
array('billingAddress' => $billingAddressSignature)

The above array returned from PaymentMethodGateway::baseSignature() does not include the fields for passing in raw credit card information like number or cvv, which the docs indicate it should:
https://developers.braintreepayments.com/javascript+php/reference/request/payment-method/create

If you compare PaymentMethotd::baseSignature()'s allowable keys to to the allowable keys for the Braintree_CreditCard::create() function, you'll see that the Braintree_CreditCard::baseSiganture() function has the credit card keys which seem to be missing from PaymentMethodGateway::baseSignature():
https://github.com/braintree/braintree_php/blob/master/lib/Braintree/CreditCardGateway.php#L335

**Comment by openbl** [comment]
I see what you're saying now. I agree that it appears `number` and other arguments are missing from `Braintree_PaymentMethod::create()` as the reference docs would seem to suggest. We'll get this added and out in our next release. Thank you for bringing this to our attention.

**Comment by dewyze** [comment]
@kevinkyao Closing this issue, it was added [here in 2.38.0](https://github.com/braintree/braintree_php/blob/4315dd2f3549cb2e9a871bd03a29ed77a6addd15/tests/unit/PaymentMethodTest.php#L15-L24). Thanks for pointing this out!

**Comment by kevinkyao** [comment]
Perhaps I don't understand the intended use of these credit card fields in the ``BraintreeaymentMethod::create()`` context.

I tested the fix but there still seems to be an issue with using ``Braintree_PaymentMethod::create()`` to directly add a credit card to the vault. 

When I pass in the credit card fields without a nonce, I get an error message "Nonce is required".  However, in the use case where one wants to use ``Braintree_PaymentMethod::Create()`` to directly add a credit card to a vault, there is no nonce available, since if there was a nonce, there would be no need to pass in the credit card fields as they would have already been encapsulated in the nonce.

Shouldn't the nonce not be a required field if the credit card fields are passed in?

**Comment by dewyze** [comment]
@kevinkyao You are correct, thanks for pointing that out. I will look into that further.

**Comment by dewyze** [comment]
@kevinkyao The docs are incorrect. Payment Method create does not accept the same parameters as a credit card. Merchants should be using payment method create with a nonce to create cards. [CreditCard create](https://developers.braintreepayments.com/javascript+php/reference/request/credit-card/create#number) using numbers should rarely be done. It creates many PCI concerns and we encourage creating via a nonce, in which PaymentMethod create would be a 'drop-in' replacement of sorts for credit card.

I realize the credit card create with numbers is often used in the sandbox environment to simulate a [variety of failures](https://developers.braintreepayments.com/javascript+php/guides/credit-cards#testing). We're looking into alternative ways to simulate those same issues via nonces.
