### ISSUE TITLE
Subscription Update Documentation Inaccurate, Drop-In UI Needs Payment Token

### ISSUE THREAD

**Issue by ReservedDeveloper** [braintree/braintree_php#68]
Currently have a site utilizing PHP + JS SDK (via DropIn UI).

According to the current [PHP SDK Docs](https://developers.braintreepayments.com/javascript+php/sdk/server/recurring-billing/update#updateable-fields), one of the fields that can be updated for a subscription is paymentMethodToken, which can be `by token or payment method nonce`. 

However, when passing a valid/unprocessed nonce to this call, a `Braintree_Exception_NotFound()` error is thrown. Per [Payment Method Documentation](https://developers.braintreepayments.com/javascript+php/sdk/server/payment-method-management/search#single-payment-method), this exception is thrown when a payment method cannot be located.

This suggests that the API does not allow for using nonce when updating subscription payment method. If that is the case, the documentation should be updated and the DropIn UI should be updated in such a way that the client can determine which payment method was added (since, presently, only a nonce is sent back by the client).

**Comment by ReservedDeveloper** [comment]
Per [this comment](http://stackoverflow.com/a/29631491/4375304) on StackOverflow, the documentation needs to be updated to reflect that, when passing a nonce, `paymentMethodNonce` must be the parameter name, not `paymentMethodToken` as shown in the example.

**Comment by ryanjpodonnell** [comment]
Hello @ReservedDeveloper,

Thank you for bringing this to our attention. Our docs team is reviewing this for possible improvements.

Best,
Ryan
