### ISSUE TITLE
using Laravel 5

### ISSUE THREAD

**Issue by infacq** [braintree/braintree_php#70]
can you show us an options for loading this in Laravel environment?

**Comment by eusonlito** [comment]
Try my Namespaces and PSR-4 compatible version: https://github.com/eusonlito/braintree_php

In your `.env` file:

```
BRAINTREE_ENVIRONMENT=sandbox
BRAINTREE_MERCHANTID=XXXXXXXXXXXXXXXXXx
BRAINTREE_PUBLICKEY=XXXXXXXXXXXXXXXXXx
BRAINTREE_PRIVATEKEY=XXXXXXXXXXXXXXXXXx
```

Then, load it with:

```php
use Braintree;

Braintree\Configuration::reset();
Braintree\Configuration::environment(env('BRAINTREE_ENVIRONMENT'));
Braintree\Configuration::merchantId(env('BRAINTREE_MERCHANTID'));
Braintree\Configuration::publicKey(env('BRAINTREE_PUBLICKEY'));
Braintree\Configuration::privateKey(env('BRAINTREE_PRIVATEKEY'));

# Usage examples

Braintree\ClientToken::generate();
Braintree\Customer::find($data);
Braintree\Customer::create($data);
Braintree\PaymentMethod::update($data['token'], $data);
```

**Comment by infacq** [comment]
thanks @eusonlito . I have figure out myself. Actually I just can call simply like this in controllers

````php
use Braintree_Configuration;
````

and can use to set the basic requirements

````php
Braintree_Configuration::privateKey(\Config::get('braintree.privateKey'));
````

i'm creating a new file braintree.php in config folder so that I can save all the basic information. Is there anyway else which you think better

**Comment by dewyze** [comment]
@infacq This seems to have been resolved, feel free to reopen if necessary.
