### ISSUE TITLE
Sub merchant account creation issue?

### ISSUE THREAD

**Issue by Nathan-Srivi** [braintree/braintree_php#72]
I want to create new merchant account from my account and i need to send money to that sub accounts using php. so i have create a file. my file link is given below.

https://gist.github.com/Nathan-Srivi/7010e94b7e74295550d1

But i unable to create sub account from this file. 

i got this script from the following link
https://github.com/braintree/braintree_php/blob/master/tests/integration/MerchantAccountTest.php

when i run my file means
i got the the following issues

`[message] =&gt; Master merchant account ID is invalid.`

I am using sandbox account. so please help me. how can i create merchant sub account and how can i transfer the account from my merchant account to merchant sub account using php.

**Comment by dewyze** [comment]
From your gist it looks like you are passing `sandbox_master_merchant_account` as your `masterMerchantAccountId`. That is a testing value. Instead, you should pass your actual master merchant account id.

For future questions more specific to your integration we recommend you reach out to support@braintreepayments.com. They will be able to better assist you with your individual integration.

**Comment by Nathan-Srivi** [comment]
Hi dewyze, 

Thanks for your reply,
may i know where i get the `masterMerchantAccountId` can you please guide me. Now i have sandbox account. My merchant id : `pgd5mp9hwy86jk52` can you please guide me

**Comment by dewyze** [comment]
@Nathan-Srivi in your sandbox you can click on Settings > Processing. Scroll to the bottom and click on "View all Merchant Accounts". That will list your merchant accounts and specify which is the master merchant account id.

GitHub isn't really a good forum for general troubleshooting questions since there can be a long delay before answering. I'd recommend our support team. If you have further issues on this matter, you will be able to get a more timely and focused response by reaching out to support@braintreepayments.com.

**Comment by praveshphp** [comment]
@dewyze I am trying same as you said but I got same error. I put correct masterMerchantAccountId in code

**Comment by dks295** [comment]
I am getting the same error.
Master merchant account ID is invalid.

in sandbox mode.
Is anyone here to resolve this issue?

**Comment by dewyze** [comment]
@praveshphp @dks295 These issues usually are more specific to each merchant and not related to the client library. In order to get better and more timely solutions, I recommend you contact support@braintreepayments.com. They will be able to work with you individually to solve your specific issue.

**Comment by appliconic1** [comment]
I have the same issue :(

**Comment by dewyze** [comment]
@appliconic1 Please contact support@braintreepayments.com. These issues are usually specific to each merchant not related to the client library. Support will be able to help you debug your specific issue.

### Note
If anyone else encounters this issue, please contact our support team. Usually the causes for this are specific to each merchant and may require different methods of troubleshooting.

**Comment by appliconic1** [comment]
thanks @dewyze  i have contacted Braintree support and got this reply; I have solved my issue and maybe it will helpful for others if they have same issue.

"Because Marketplace is only supported in the US, and you signed up for your sandbox outside of the US, your sandbox isn't a Marketplace account. If you are a developer working for a US based merchant on an integration, you will need to signup for a US sandbox account. You can do this on our website by selecting United States as your country using the drop down menu on the bottom left of the page. You should then be able to click the Try the Sandbox button and sign up for a new sandbox account with Marketplace features enabled. This should allow you to create sub-merchant accounts using a master merchant account, which will exist if a new sandbox is created following the directions I've supplied.
Once you have a Marketplace sandbox, your default merchant account will also be your Master Merchant account. You can locate your merchant account ID and their types by following these steps:

Log in to the Control Panel
Navigate to Settings → Processing
Scroll to the bottom of the page to find the section labeled Merchant Accounts
Click the "View all Merchant Accounts" button
You'll specify both your Master Merchant account ID and the id of your new sub-merchant in the API call.
I hope this clarifies! Please let us know if you have further questions.
"

**Comment by Streemo** [comment]
You are using your Merchant ID from the Dashboard (of the form "vj7hcbfjktygp4sl"), and it isn't working.

Solution:

3. Go to settings in the upper right nav menu on the Dashboard page.
3. Click processing.
4. Scroll to the bottom.
5. Click the big button called "New sandbox merchant account"
6. Check the box which says "Make this a Marketplace Master merchant account."
7. Now use this in the `masterMerchantAccountId` field in the method.
8. Don't forget to pass in a value of `"approve_me"` as the `firstName` of the individual.

This worked for me.

**Comment by jestintab** [comment]
@Streemo Could please explain the step 8. Can you please share your code too .. Thanks in advance

**Comment by bhalodiasandip** [comment]
@Streemo regarding your 5th step. I try to create merchant account for US from dashboard. I can't find this checkbox option "Make this a Marketplace Master merchant account." I also asked to support team to enable this merchant account. they replied that "All sandbox accounts are enabled for Marketplace by default." Although I am getting same error. "Master merchant account ID is invalid"

**Comment by jestintab** [comment]
@bhalodiasandip there is a option below select ur country in the left side of footer make sure you have selected 'US' in there. I was getting same error. I tried like this and it worked. :smile:

**Comment by shreeya-detroja** [comment]
Sorry, but I can't found select country dropbox on the left side of footer.

**Comment by shreeya-detroja** [comment]
I am also not able to find a checkbox option "Make this a Marketplace Master merchant account."

**Comment by bhalodiasandip** [comment]
Shreeya,
check this link https://www.braintreepayments.com/get-started

**Comment by bhalodiasandip** [comment]
Shreeya,
To resolve your problem you should create new sandbox account follow these steps.
1) check this link https://www.braintreepayments.com/get-started.
2) Scroll page down at bottom. you can find country selection area at left-bottom. Select US from it.
3) Then enter registration detail in form.
4) New account will automatically marketplace account.
Enjoy..

**Comment by shreeya-detroja** [comment]
hey sandip, thanks

**Comment by shreeya-detroja** [comment]
I solved this issue, but now arrise new issue.
Now i can view a list of Master-merchant and sub-merchant accounts,
so when i set the value of 
masterMerchantAccountId='master_merchant_value' & id='sub_merchant' in create function parameter, at that time will return error like : Applicant merchant id is in use.
error code : 82604

**Comment by bhalodiasandip** [comment]
Shreeya,

**Comment by shreeya-detroja** [comment]
Yes, give a solution if you have.

**Comment by bhalodiasandip** [comment]
Shreeya, I hope that you are using proper masterMerchantAccountId = Merchant Account ID that are listing in your dashboard under Merchant Accounts section. ID parameter is optional. You can skeep it. If you want to generate submerchant with specific ID then you can mention ID that is different from your master merchant account id. or don't pass id parameter while create submerchant.

**Comment by shreeya-detroja** [comment]
Hey sandip,
Shreeya here,
New issue with webhook.

I m trying to validate sub-merchant-account that it is valid or not which
is entered by third party,
So for that I created webhook for sub-merchant-account on control-panel,
From that I can also fetch the value of bt_signature and bt_upload,
i applied that value to below code.
$sampleNotification = Braintree_WebhookTesting::sampleNotification(
Braintree_WebhookNotification::SUBSCRIPTION_WENT_PAST_DUE, 'my_id'
);
$notification = Braintree_WebhookNotification::parse(
$sampleNotification['bt_signature'], $sampleNotification['bt_payload']
);
But it return an error : Undefined property on
Braintree_WebhookNotification: merchantAccount
So, How could i validate merchant account is exist or not?
and what would be the value of my_id?
what would be the value of api configuration? (It should be the
master-merchant-account api?)
I m using cakephp.

Please help, need to be finished today.
Thanks in advance.

**Comment by matthewarkin** [comment]
@shreeya-detroja The sampleNotification you're using is for `SUBSCRIPTION_WENT_PAST_DUE`, you can view the list of supported sample notifications at https://github.com/braintree/braintree_php/blob/36c2b9de6793a28e25f5f9e265f60aaffef2cfe2/lib/Braintree/WebhookTesting.php#L20 the ones you care about are `SUB_MERCHANT_ACCOUNT_APPROVED` and `SUB_MERCHANT_ACCOUNT_DECLINED`

**Comment by matthewarkin** [comment]
@shreeya-detroja The sampleNotification you're using is for `SUBSCRIPTION_WENT_PAST_DUE`, you can view the list of supported sample notifications at https://github.com/braintree/braintree_php/blob/36c2b9de6793a28e25f5f9e265f60aaffef2cfe2/lib/Braintree/WebhookTesting.php#L20 the ones you care about are `SUB_MERCHANT_ACCOUNT_APPROVED` and `SUB_MERCHANT_ACCOUNT_DECLINED`

**Comment by pbogomyagkov** [comment]
I still have this f**king god damn bullsh*t error "Master merchant account ID is invalid.". sorry for may french
