### ISSUE TITLE
Serialize Braintree objects

### ISSUE THREAD

**Issue by stevro** [braintree/braintree_php#73]
Why Braintree objects are not serializable? Our applications could benefit from storing a serialized version of Braintree_Transaction and/or Braintree_Subscription. This would help us to improve customer support, and debugging in production, because just saving the string version isn't enough, and saving by hand all the attributes is cumbersome.

**Comment by matthewpatterson** [comment]
Hi @stevro, thanks for bringing this up! If you wouldn't mind, how are you trying to serialize Braintree objects? I did a quick test of this and it seems that `Braintree_Transaction` objects can be serialized:

```php
public function testTransactionIsSerializable()
{
    $t = Braintree_Transaction::factory(array(
        'creditCard' => array('expirationMonth' => '05', 'expirationYear' => '2020', 'bin' => '411111', 'last4' => '1111'),
        'customer' => array(),
        'billing' => array(),
        'descriptor' => array(),
        'shipping' => array(),
        'subscription' => array('billingPeriodStartDate' => '1983-07-12'),
        'statusHistory' => array()
    ));

    $this->assertInternalType('string', serialize($t));

    $unserialized = unserialize(serialize($t));
    $this->assertInstanceOf('Braintree_Transaction', $unserialized);
    $this->assertEquals($t->creditCard, $unserialized->creditCard);
}
```

**Comment by stevro** [comment]
When I test with an object received from Braintree API I get Notice: unserialize(): Error at offset 3979 of 6445 bytes. I'm serializing a Braintree_Transaction object and I store it in a blob column in mysql.

This is how my object looks like after serialization.

O:21:"Braintree_Transaction":1:{s:11:"_attributes";a:53:{s:2:"id";s:6:"f2tqhj";s:6:"status";s:24:"submitted_for_settlement";s:4:"type";s:4:"sale";s:15:"currencyIsoCode";s:3:"USD";s:6:"amount";s:5:"20.00";s:17:"merchantAccountId";s:16:"obfuscated";s:7:"orderId";N;s:9:"createdAt";O:8:"DateTime":3:{s:4:"date";s:19:"2015-05-14 15:21:42";s:13:"timezone_type";i:3;s:8:"timezone";s:3:"UTC";}s:9:"updatedAt";O:8:"DateTime":3:{s:4:"date";s:19:"2015-05-14 15:21:42";s:13:"timezone_type";i:3;s:8:"timezone";s:3:"UTC";}s:8:"customer";a:8:{s:2:"id";s:2:"26";s:9:"firstName";s:3:"asd";s:8:"lastName";s:3:"asd";s:7:"company";N;s:5:"email";s:28:"stefan+27@intelligentbee.com";s:7:"website";N;s:5:"phone";N;s:3:"fax";N;}s:7:"billing";a:13:{s:2:"id";N;s:9:"firstName";N;s:8:"lastName";N;s:7:"company";N;s:13:"streetAddress";N;s:15:"extendedAddress";N;s:8:"locality";N;s:6:"region";N;s:10:"postalCode";N;s:11:"countryName";N;s:17:"countryCodeAlpha2";N;s:17:"countryCodeAlpha3";N;s:18:"countryCodeNumeric";N;}s:8:"refundId";N;s:9:"refundIds";a:0:{}s:21:"refundedTransactionId";N;s:17:"settlementBatchId";N;s:8:"shipping";a:13:{s:2:"id";N;s:9:"firstName";N;s:8:"lastName";N;s:7:"company";N;s:13:"streetAddress";N;s:15:"extendedAddress";N;s:8:"locality";N;s:6:"region";N;s:10:"postalCode";N;s:11:"countryName";N;s:17:"countryCodeAlpha2";N;s:17:"countryCodeAlpha3";N;s:18:"countryCodeNumeric";N;}s:12:"customFields";s:0:"";s:20:"avsErrorResponseCode";N;s:25:"avsPostalCodeResponseCode";s:1:"I";s:28:"avsStreetAddressResponseCode";s:1:"I";s:15:"cvvResponseCode";s:1:"I";s:22:"gatewayRejectionReason";N;s:26:"processorAuthorizationCode";s:6:"CN63V0";s:21:"processorResponseCode";s:4:"1000";s:21:"processorResponseText";s:8:"Approved";s:27:"additionalProcessorResponse";N;s:19:"voiceReferralNumber";N;s:19:"purchaseOrderNumber";N;s:9:"taxAmount";N;s:9:"taxExempt";b:0;s:10:"creditCard";a:20:{s:5:"token";s:35:"obfuscated";s:3:"bin";s:6:"401200";s:5:"last4";s:4:"7777";s:8:"cardType";s:4:"Visa";s:15:"expirationMonth";s:2:"12";s:14:"expirationYear";s:4:"2020";s:16:"customerLocation";s:2:"US";s:14:"cardholderName";N;s:8:"imageUrl";s:84:"https://assets.braintreegateway.com/payment_method_logo/visa.png?environment=sandbox";s:22:"uniqueNumberIdentifier";s:32:"obfuscated";s:7:"prepaid";s:7:"Unknown";s:10:"healthcare";s:7:"Unknown";s:5:"debit";s:7:"Unknown";s:15:"durbinRegulated";s:7:"Unknown";s:10:"commercial";s:7:"Unknown";s:7:"payroll";s:7:"Unknown";s:11:"issuingBank";s:7:"Unknown";s:17:"countryOfIssuance";s:7:"Unknown";s:9:"productId";s:7:"Unknown";s:8:"venmoSdk";b:0;}s:13:"statusHistory";a:2:{i:0;O:35:"Braintree_Transaction_StatusDetails":1:{s:11:"_attributes";a:5:{s:9:"timestamp";O:8:"DateTime":3:{s:4:"date";s:19:"2015-05-14 15:21:42";s:13:"timezone_type";i:3;s:8:"timezone";s:3:"UTC";}s:6:"status";s:10:"authorized";s:6:"amount";s:5:"20.00";s:4:"user";s:12:"user_obfuscated";s:17:"transactionSource";s:9:"recurring";}}i:1;O:35:"Braintree_Transaction_StatusDetails":1:{s:11:"_attributes";a:5:{s:9:"timestamp";O:8:"DateTime":3:{s:4:"date";s:19:"2015-05-14 15:21:42";s:13:"timezone_type";i:3;s:8:"timezone";s:3:"UTC";}s:6:"status";s:24:"submitted_for_settlement";s:6:"amount";s:5:"20.00";s:4:"user";s:12:"user_obfuscated";s:17:"transactionSource";s:9:"recurring";}}}s:6:"planId";s:4:"8vdw";s:14:"subscriptionId";s:2:"26";s:12:"subscription";a:2:{s:20:"billingPeriodEndDate";O:8:"DateTime":3:{s:4:"date";s:19:"2015-06-13 00:00:00";s:13:"timezone_type";i:3;s:8:"timezone";s:3:"UTC";}s:22:"billingPeriodStartDate";O:8:"DateTime":3:{s:4:"date";s:19:"2015-05-14 00:00:00";s:13:"timezone_type";i:3;s:8:"timezone";s:3:"UTC";}}s:6:"addOns";a:0:{}s:9:"discounts";a:0:{}s:10:"descriptor";O:20:"Braintree_Descriptor":1:{s:11:"_attributes";a:3:{s:4:"name";N;s:5:"phone";N;s:3:"url";N;}}s:9:"recurring";b:1;s:7:"channel";N;s:16:"serviceFeeAmount";N;s:12:"escrowStatus";N;s:19:"disbursementDetails";O:29:"Braintree_DisbursementDetails":1:{s:14:"\00*\00_attributes";a:6:{s:16:"disbursementDate";N;s:16:"settlementAmount";N;s:25:"settlementCurrencyIsoCode";N;s:30:"settlementCurrencyExchangeRate";N;s:9:"fundsHeld";N;s:7:"success";N;}}s:8:"disputes";a:0:{}s:21:"paymentInstrumentType";s:11:"credit_card";s:31:"processorSettlementResponseCode";s:0:"";s:31:"processorSettlementResponseText";s:0:"";s:16:"threeDSecureInfo";N;s:17:"creditCardDetails";O:39:"Braintree_Transaction_CreditCardDetails":1:{s:14:"\00*\00_attributes";a:22:{s:5:"token";s:35:"token_obfuscated";s:3:"bin";s:6:"401200";s:5:"last4";s:4:"7777";s:8:"cardType";s:4:"Visa";s:15:"expirationMonth";s:2:"12";s:14:"expirationYear";s:4:"2020";s:16:"customerLocation";s:2:"US";s:14:"cardholderName";N;s:8:"imageUrl";s:84:"https://assets.braintreegateway.com/payment_method_logo/visa.png?environment=sandbox";s:22:"uniqueNumberIdentifier";s:32:"cf44442928862d0d0ec280ddc7daafd1";s:7:"prepaid";s:7:"Unknown";s:10:"healthcare";s:7:"Unknown";s:5:"debit";s:7:"Unknown";s:15:"durbinRegulated";s:7:"Unknown";s:10:"commercial";s:7:"Unknown";s:7:"payroll";s:7:"Unknown";s:11:"issuingBank";s:7:"Unknown";s:17:"countryOfIssuance";s:7:"Unknown";s:9:"productId";s:7:"Unknown";s:8:"venmoSdk";b:0;s:14:"expirationDate";s:7:"12/2020";s:12:"maskedNumber";s:16:"401200******7777";}}s:15:"customerDetails";O:37:"Braintree_Transaction_CustomerDetails":1:{s:11:"_attributes";a:8:{s:2:"id";s:2:"26";s:9:"firstName";s:3:"asd";s:8:"lastName";s:3:"asd";s:7:"company";N;s:5:"email";s:28:"stefan+27@intelligentbee.com";s:7:"website";N;s:5:"phone";N;s:3:"fax";N;}}s:14:"billingDetails";O:36:"Braintree_Transaction_AddressDetails":1:{s:14:"\00*\00_attributes";a:13:{s:2:"id";N;s:9:"firstName";N;s:8:"lastName";N;s:7:"company";N;s:13:"streetAddress";N;s:15:"extendedAddress";N;s:8:"locality";N;s:6:"region";N;s:10:"postalCode";N;s:11:"countryName";N;s:17:"countryCodeAlpha2";N;s:17:"countryCodeAlpha3";N;s:18:"countryCodeNumeric";N;}}s:15:"shippingDetails";O:36:"Braintree_Transaction_AddressDetails":1:{s:14:"\00*\00_attributes";a:13:{s:2:"id";N;s:9:"firstName";N;s:8:"lastName";N;s:7:"company";N;s:13:"streetAddress";N;s:15:"extendedAddress";N;s:8:"locality";N;s:6:"region";N;s:10:"postalCode";N;s:11:"countryName";N;s:17:"countryCodeAlpha2";N;s:17:"countryCodeAlpha3";N;s:18:"countryCodeNumeric";N;}}s:19:"subscriptionDetails";O:41:"Braintree_Transaction_SubscriptionDetails":1:{s:11:"_attributes";a:2:{s:20:"billingPeriodEndDate";r:118;s:22:"billingPeriodStartDate";r:122;}}}}

**Comment by matthewpatterson** [comment]
Hey @stevro,

It seems like `unserialize()` is breaking down at this point:

```
O:29:"Braintree_DisbursementDetails":1:{s:14:"\00\00_attributes";a:6:
                                              ^
```

This is due to the way that PHP serializes protected and private class members:

>**Note:**
>Object's private members have the class name prepended to the member name; protected members have a '*' prepended to the member name. These prepended values have null bytes on either side.

(Source: http://php.net/manual/en/function.serialize.php)

To demonstrate this in action, consider the following code:

```php
<?php
class Foo
{
    public $apple = 1;
    protected $banana = 2;
    private $cherry = 3;
}

file_put_contents('serialized.out', serialize(new Foo()));
```

Inspecting `serialized.out` shows the null bytes preceding the the `banana` and `cherry` attributes.

```
$ hexdump -C serialized.out
00000000  4f 3a 33 3a 22 46 6f 6f  22 3a 33 3a 7b 73 3a 35  |O:3:"Foo":3:{s:5|
00000010  3a 22 61 70 70 6c 65 22  3b 69 3a 31 3b 73 3a 39  |:"apple";i:1;s:9|
00000020  3a 22 00 2a 00 62 61 6e  61 6e 61 22 3b 69 3a 32  |:".*.banana";i:2|
00000030  3b 73 3a 31 31 3a 22 00  46 6f 6f 00 63 68 65 72  |;s:11:".Foo.cher|
00000040  72 79 22 3b 69 3a 33 3b  7d                       |ry";i:3;}|
00000049
```

I haven't tested interacting with a database, but it seems likely that a database would change the representation of the null bytes, resulting in the broken serialization string.

I'll look into what we can do to fix this.

**Comment by raymondberg** [comment]
Hi @stevro. We haven't been able to reproduce despite several different MySQL insert approaches, Braintree objects, column types, and string handling. As we haven't heard any others with similar problems, the best bet is that there might be an issue with your storage logic or structure. If you continue to have problems, I would advise you to open a ticket with [Braintree support](https://support.braintreepayments.com) to allow you to share more code samples and configurations (be sure to link to this issue if you do).
