### ISSUE TITLE
Fire webhooks form the sandbox control panel

### ISSUE THREAD

**Issue by vipconsult** [braintree/braintree_php#75]
Hi there.

Would you consider adding webhook triggers form the control panel?

I think this would imitate a real expected behaviour and verify that the webhook implementation on the server is correct.

**Comment by ryanjpodonnell** [comment]
Hello @vipconsult,

You are able to fire off a few webhooks using the control panel. For instance, the "Subscription went active" webhook is fireable from the control panel. Do do this, simply click on a payment method and click on the "Add Subscription" button on the page. If set up correctly, this will trigger a webhook that you can test.

If you have any other questions you can contact support@braintreepayments.com
