### ISSUE TITLE
drop in UI - issues

### ISSUE THREAD

**Issue by umulla** [braintree/braintree_php#80]
1) Lets say customer adds two cards - Card number – 4009348888881881 and 4012888888881881. 

The drop in UI when initialized with the customer ID will display the cards like 
 
![image](https://cloud.githubusercontent.com/assets/10092113/8089184/df59379c-0f6b-11e5-8c58-0f030c53af46.png)

This is confusing and defeats the purpose of allowing the customer to choose the desired card.

**Comment by ryanjpodonnell** [comment]
We only display the last 2 digits of payment methods in our Drop-in to remain PCI compliant. We do not want to expose any more information than we have to.
When testing in the sandbox, it is likely that 2 test numbers will end in the same last 2 digits; however, to my knowledge we have yet to see this issue arise in production.
If not being able to disambiguate payment methods is a concern, we encourage you to customize the credit card display using [Hosted Fields](https://developers.braintreepayments.com/javascript+ruby/guides/hosted-fields/overview) or to create a custom integration, both of which are supported by Braintree.

**Comment by umulla** [comment]
thanks for your response.
