### ISSUE TITLE
Operations that depend upon the public/private key should fail if they aren't set

### ISSUE THREAD

**Issue by ExplodingCabbage** [braintree/braintree_php#81]
For example, the `verify` method [doesn't complain](https://github.com/braintree/braintree_php/blob/master/lib/Braintree/WebhookNotification.php#L35-L43) if it's called before you've set your keys with `Braintree_Configuration::privateKey()` and `Braintree_Configuration::publicKey()`. I just spent half an hour wondering why I was constantly getting a "Destination could not be verified" error from the webhooks panel before finally realising my mistake - which the library could in principle have pointed out to me.

**Comment by crookedneighbor** [comment]
Hey @explodingCabbage, thanks for bringing this up! We're working on a fix for this; I'll let you know when it's released.

**Comment by crookedneighbor** [comment]
@ExplodingCabbage I'm happy to announce that the fix has been released!
