### ISSUE TITLE
error when submiting a transaction for refund - please advise

### ISSUE THREAD

**Issue by felixmrdx** [braintree/braintree_php#83]
<br />
<b>Fatal error</b>:  Uncaught exception 'Braintree_Exception_NotFound' in /public_html/vendor/braintree/lib/Braintree/Util.php:59
Stack trace:
#0 /public_html/vendor/braintree/lib/Braintree/Http.php(44): Braintree_Util::throwStatusCodeException(404)
#1 /public_html/vendor/braintree/lib/Braintree/TransactionGateway.php(373): Braintree_Http-&gt;post('/merchants/dvnd...', Array)
#2 /public_html/vendor/braintree/lib/Braintree/Transaction.php(492): Braintree_TransactionGateway-&gt;refund('043240', '479.94')
#3 /public_html/admin/modules/payment/braintreepayments/function_process_braintree_refund.php(98): Braintree_Transaction::refund('043240', '479.94')
#4 {main}
  thrown in <b>/public_html/vendor/braintree/lib/Braintree/Util.php</b> on line <b>59</b><br />

**Comment by wjr1985** [comment]
Hi @felixmrdx,

When submitting a refund, you will see the `Braintree_Exception_NotFound` exception when the transaction ID you specified [does not exist](https://developers.braintreepayments.com/javascript+php/reference/general/exceptions#not-found-error). Make sure you're passing in a transaction ID and not a payment method token.

If you have any additional questions on this, or need any other assistance, I recommend contacting us via email (support@braintreepayments.com) so we can take a more in-depth look at this issue.

Best,
Bill
