### ISSUE TITLE
Class SimpleXMLIterator not implemented on HHVM

### ISSUE THREAD

**Issue by frikken** [braintree/braintree_php#84]
Hi all,
the SimpleXMLIterator class, used in Braintree_Xml_Parser, seems not implemented on HHVM (https://github.com/facebook/hhvm/issues/3292), so every call results in a Fatal Error and the library is unusable on HHVM.

I have this error with braintree library 3.0.1 and HHVM 3.7.2, but maybe the problem persist for all braintree library version because the SimpleXMLIterator class is used everywhere.

I can't find this problem mentioned anywhere in your issues . . . am I missing something?

**Comment by matthewpatterson** [comment]
Hi @frikken, you are correct that the lack of `SimpleXMLIterator` prevents our library from working under HHVM currently. We have actually re-written our XML parsing logic to use the DOM component to make the library compatible with HHVM, but that change hasn't been released yet. I'll see about getting it released today or early next week.

**Comment by matthewpatterson** [comment]
This should be fixed in version 3.1.0, available on [Github](https://github.com/braintree/braintree_php/releases/tag/3.1.0) and [Packagist](https://packagist.org/packages/braintree/braintree_php). It will also be available for download on our developers website some time next week.
