### ISSUE TITLE
errors->deepAll() returning null with Braintree_Customer::create with paymentMethodNonce

### ISSUE THREAD

**Issue by vipconsult** [braintree/braintree_php#85]
the following code doesn't return the gateway error when the card fails validation

I used this card number : 378734493671000

      $params = array(
            "company" => element('name',$data),
            'paymentMethodNonce' => $data['payment_method_nonce'],
            'customFields' => array(
                'id_company' => $data['id_company'],
                'reference' => $data['reference'],
            )
        );
        
        $gateway_response=Braintree_Customer::create($params);

       foreach($gateway_response->errors->deepAll() AS $error) {
            print_r($error->code . ": " . $error->message . "\n");
       }

**Comment by openbl** [comment]
@vipconsult, the card will not be gateway rejected if the argument `'verifyCard' => true` isn't passed in the server-side API call. If you follow our docs on how to run [a verification via a `Braintree_Customer::create()` call](https://developers.braintreepayments.com/reference/request/customer/create#card-verification), you should see the verification errors in the result object.

**Comment by vipconsult** [comment]
Card Verification is globally enabled and the gateway reply returns an error , just the deepAll doesn't extract all errors

**Comment by openbl** [comment]
What do you see when you run `print_r($gateway_response);`?

**Comment by vipconsult** [comment]
Braintree_Result_Error Object
(
    [success] => 
    [_attributes] => Array
        (
            [errors] => Braintree_Error_ErrorCollection Object
                (
                    [_errors:Braintree_Error_ErrorCollection:private] => Braintree_Error_ValidationErrorCollection Object
                        (
                            [_errors:Braintree_Error_ValidationErrorCollection:private] => Array
                                (
                                )

                            [_nested:Braintree_Error_ValidationErrorCollection:private] => Array
                                (
                                    [paymentMethod] => Braintree_Error_ValidationErrorCollection Object
                                        (
                                            [_errors:Braintree_Error_ValidationErrorCollection:private] => Array
                                                (
                                                )

                                            [_nested:Braintree_Error_ValidationErrorCollection:private] => Array
                                                (
                                                )

                                            [_collection:protected] => Array
                                                (
                                                )

                                        )

                                    [creditCard] => Braintree_Error_ValidationErrorCollection Object
                                        (
                                            [_errors:Braintree_Error_ValidationErrorCollection:private] => Array
                                                (
                                                )

                                            [_nested:Braintree_Error_ValidationErrorCollection:private] => Array
                                                (
                                                )

                                            [_collection:protected] => Array
                                                (
                                                )

                                        )

                                )

                            [_collection:protected] => Array
                                (
                                )

                        )

                )

            [params] => Array
                (
                    [customer] => Array
                        (
                            [company] => false
                            [paymentMethodNonce] => b11b1fcd-a240-45b9-baa2-0df30a129c59
                            [customFields] => Array
                                (
                                    [id_company] => 14
                                    [reference] => sad
                                )

                        )

                )

            [message] => Do Not Honor
            [verification] => Array
                (
                    [status] => processor_declined
                    [cvvResponseCode] => M
                    [avsErrorResponseCode] => 
                    [avsPostalCodeResponseCode] => I
                    [avsStreetAddressResponseCode] => I
                    [gatewayRejectionReason] => 
                    [merchantAccountId] => 8b31189c34184491d7a9a6abdac98495
                    [processorResponseCode] => 2000
                    [processorResponseText] => Do Not Honor
                    [id] => 9sj7nj
                    [billing] => Array
                        (
                            [firstName] => 
                            [lastName] => 
                            [company] => 
                            [streetAddress] => 
                            [extendedAddress] => 
                            [locality] => 
                            [region] => 
                            [postalCode] => 
                            [countryName] => 
                        )

                    [creditCard] => Array
                        (
                            [token] => 
                            [bin] => 378734
                            [last4] => 1000
                            [cardType] => American Express
                            [expirationMonth] => 12
                            [expirationYear] => 2021
                            [customerLocation] => US
                            [cardholderName] => 
                            [uniqueNumberIdentifier] => 481ed5b002750ad7b7f1275c9da98ff6
                            [prepaid] => Unknown
                            [healthcare] => Unknown
                            [debit] => Unknown
                            [durbinRegulated] => Unknown
                            [commercial] => Unknown
                            [payroll] => Unknown
                            [issuingBank] => Unknown
                            [countryOfIssuance] => Unknown
                            [productId] => Unknown
                        )

                    [createdAt] => DateTime Object
                        (
                            [date] => 2015-07-10 17:57:12.000000
                            [timezone_type] => 3
                            [timezone] => UTC
                        )

                    [updatedAt] => DateTime Object
                        (
                            [date] => 2015-07-10 17:57:12.000000
                            [timezone_type] => 3
                            [timezone] => UTC
                        )

                )

            [creditCardVerification] => Braintree_Result_CreditCardVerification Object
                (
                    [_attributes:Braintree_Result_CreditCardVerification:private] => Array
                        (
                            [status] => processor_declined
                            [cvvResponseCode] => M
                            [avsErrorResponseCode] => 
                            [avsPostalCodeResponseCode] => I
                            [avsStreetAddressResponseCode] => I
                            [gatewayRejectionReason] => 
                            [merchantAccountId] => 8b31189c34184491d7a9a6abdac98495
                            [processorResponseCode] => 2000
                            [processorResponseText] => Do Not Honor
                            [id] => 9sj7nj
                            [billing] => Array
                                (
                                    [firstName] => 
                                    [lastName] => 
                                    [company] => 
                                    [streetAddress] => 
                                    [extendedAddress] => 
                                    [locality] => 
                                    [region] => 
                                    [postalCode] => 
                                    [countryName] => 
                                )

                            [creditCard] => Array
                                (
                                    [token] => 
                                    [bin] => 378734
                                    [last4] => 1000
                                    [cardType] => American Express
                                    [expirationMonth] => 12
                                    [expirationYear] => 2021
                                    [customerLocation] => US
                                    [cardholderName] => 
                                    [uniqueNumberIdentifier] => 481ed5b002750ad7b7f1275c9da98ff6
                                    [prepaid] => Unknown
                                    [healthcare] => Unknown
                                    [debit] => Unknown
                                    [durbinRegulated] => Unknown
                                    [commercial] => Unknown
                                    [payroll] => Unknown
                                    [issuingBank] => Unknown
                                    [countryOfIssuance] => Unknown
                                    [productId] => Unknown
                                )

                            [createdAt] => DateTime Object
                                (
                                    [date] => 2015-07-10 17:57:12.000000
                                    [timezone_type] => 3
                                    [timezone] => UTC
                                )

                            [updatedAt] => DateTime Object
                                (
                                    [date] => 2015-07-10 17:57:12.000000
                                    [timezone_type] => 3
                                    [timezone] => UTC
                                )

                        )

                    [_avsErrorResponseCode:Braintree_Result_CreditCardVerification:private] => 
                    [_avsPostalCodeResponseCode:Braintree_Result_CreditCardVerification:private] => I
                    [_avsStreetAddressResponseCode:Braintree_Result_CreditCardVerification:private] => I
                    [_cvvResponseCode:Braintree_Result_CreditCardVerification:private] => M
                    [_gatewayRejectionReason:Braintree_Result_CreditCardVerification:private] => 
                    [_status:Braintree_Result_CreditCardVerification:private] => processor_declined
                    [_merchantAccountId] => 8b31189c34184491d7a9a6abdac98495
                    [_processorResponseCode] => 2000
                    [_processorResponseText] => Do Not Honor
                    [_id] => 9sj7nj
                    [_billing] => Array
                        (
                            [firstName] => 
                            [lastName] => 
                            [company] => 
                            [streetAddress] => 
                            [extendedAddress] => 
                            [locality] => 
                            [region] => 
                            [postalCode] => 
                            [countryName] => 
                        )

                    [_creditCard] => Array
                        (
                            [token] => 
                            [bin] => 378734
                            [last4] => 1000
                            [cardType] => American Express
                            [expirationMonth] => 12
                            [expirationYear] => 2021
                            [customerLocation] => US
                            [cardholderName] => 
                            [uniqueNumberIdentifier] => 481ed5b002750ad7b7f1275c9da98ff6
                            [prepaid] => Unknown
                            [healthcare] => Unknown
                            [debit] => Unknown
                            [durbinRegulated] => Unknown
                            [commercial] => Unknown
                            [payroll] => Unknown
                            [issuingBank] => Unknown
                            [countryOfIssuance] => Unknown
                            [productId] => Unknown
                        )

                    [_createdAt] => DateTime Object
                        (
                            [date] => 2015-07-10 17:57:12.000000
                            [timezone_type] => 3
                            [timezone] => UTC
                        )

                    [_updatedAt] => DateTime Object
                        (
                            [date] => 2015-07-10 17:57:12.000000
                            [timezone_type] => 3
                            [timezone] => UTC
                        )

                )

            [transaction] => 
            [subscription] => 
            [merchantAccount] => 
        )

)

**Comment by openbl** [comment]
It would appear that `deepAll()` isn't working the way I'd expect. I'll reopen and take a look at this closer. Thanks for letting us know.

**Comment by openbl** [comment]
After further investigation, this is not an issue w/ `deepAll()` but poor documentation around how to access the `creditCardVerification` when a verification fails. If you take a look at [our reference docs](https://developers.braintreepayments.com/reference/request/customer/create#validation-results), `$gateway_response->success` will be `false` but you need to use `$gateway_response->creditCardVerification`, which is a sibling attribute to `$gateway_response->errors`, to access the verification response.

Thank you for illustrating the needed improvement around that topic. I'm going to make sure we improve the documentation around verification responses.
