### ISSUE TITLE
Braintree_Exception_NotFound triggered by : Braintree_Transaction::refund returns empty message

### ISSUE THREAD

**Issue by vipconsult** [braintree/braintree_php#86]
when I run transaction refund method with a non existent transaction it throws an error but the exception returns an empty message so cannot display the error to the gui 

Braintree_Transaction::refund('nonExistent');

as a workaround i run         
Braintree_Transaction::find('nonExistent');

which throws an exception with an error, but if possible I would prefer to run a single api call.

catch(Exception $e){
     print_r($e->getMessage());
}

**Comment by ryanjpodonnell** [comment]
Our [logic](https://github.com/braintree/braintree_php/blob/master/lib/Braintree/Util.php#L58) purposely throws an error without a message when we receive a `404` after posting to our Gateway.

If you need a message with an error I do not see anything wrong with making an extra api call. You could also catch on the `Braintree_Exception_NotFound` during a Transaction#refund and print out a personalized message.

Our exceptions are not built to be customer facing but rather are built for our merchants.
