### ISSUE TITLE
SSL_Braintree Exception on checkout page

### ISSUE THREAD

**Issue by aniruddhashinde** [braintree/braintree_php#87]
Hi,

I am using  the following plugin (woocommerce-gateway-braintree) by WooThemes and it is not working as it throws a SSL exception after you submit the card details. I tried reinstalling the SSL certificate on my domain again but it still throws the same exception. I tried SandBox and production both and it throws the same exception. Below is the exception:
"An error occurred, please try again or try an alternate form of payment.
Error Type Braintree_Exception_SSLCertificate"

Website link: www.rowdyjewellery.com

**Comment by maxrice** [comment]
hey @aniruddhashinde I'm one of the developers for the WooCommerce Braintree gateway -- I think this exception is raised when certificate validation fails (see [this](https://github.com/braintree/braintree_php/blob/master/lib/Braintree/Exception/SSLCertificate.php)). Check the cURL config on your server and make sure it's not overriding the CA in some way.

**Comment by aniruddhashinde** [comment]
Hi Max,

Thank you for your prompt reply. I am a little new to this, I tried to
google on how to configure cURL but couldn't find the required information
as most of the solutions are for local server. However in my case my
website is already online and hosted with dnsIreland. I am unable to figure
out where do I make this change.
Can you please assist me with the same?


Regards,

Aniruddha Shinde

**Comment by maxrice** [comment]
Best to [create a ticket](https://woothemes.com/my-account/create-a-ticket/) over at WooThemes so their support team can assist :)
