### ISSUE TITLE
BTBraintreeAPIErrorDomain Code=0 

### ISSUE THREAD

**Issue by allen8300** [braintree/braintree_php#89]
Hi there, I'm testing in live mode, and I kept getting this error when trying to pay by paypal and ApplePay.
Hope you can reply soon. Thanks in advance.
![screen shot 2015-08-01 at 1 43 00 am](https://cloud.githubusercontent.com/assets/1751906/9013714/47f1130e-37f0-11e5-9d47-32cb538a9949.png)

**Comment by raymondberg** [comment]
Hi, @allen8300! I'm sorry to hear you're having troubles! I hope that you've opened a ticket with support to try to identify/resolve the issue. 

I'm going to close this issue as we typically focus on client-library source code issues and this could be related to any number of problems between your client and our service. If you are still having issues like this [please reach out to support](https://support.braintreepayments.com/).
