### ISSUE TITLE
Semantic Versioning (SemVer)

### ISSUE THREAD

**Issue by madu2789** [braintree/braintree_php#91]
Hi,

I've seen at the changelog that the change of 3.0.0 to 3.0.1 add a feature (Add support for Android Pay), then i suppose that braintree_php doesn't follow semantic versioning? Thanks!

**Comment by raymondberg** [comment]
@madu2789 We do support semantic versioning but that version was annotated incorrectly. Thanks for keeping us honest!

**Comment by madu2789** [comment]
Thanks!
