### ISSUE TITLE
Single namespace for 'use' syntax?

### ISSUE THREAD

**Issue by GiantCowFilms** [braintree/braintree_php#94]
Recent versions of  PHP (I'm not sure how far back this functionality goes)  allow programmers to load files by namespace instead of using requires. This makes for much easier management of dependencies with composer, and is vital to the functionality of many frameworks. In the case of the Braintree PHP SDK, This feature is nearly present with psr-0 auto loading with one exception. It requires that *every single class* be explicitly used. There are at least 20 of them. It is quite ridiculous to load them all. This all could be fixed by creating a braintree namespace, which then could be used with `use Braintree`. That would make things much simpler, and would make the SDK more in keeping with the way composer functions. Thanks

**Comment by GiantCowFilms** [comment]
Also psr-4 would be nice :D competitors such as stripe are using it...

**Comment by eusonlito** [comment]
Check my fork https://github.com/eusonlito/braintree_php

It's working and updated to 3.1.0 release (Will be updated to 3.3.0 ASAP).

**Comment by GiantCowFilms** [comment]
@eusonlito  Quite cool!

**Comment by LukeXF** [comment]
+1 @GiantCowFilms

**Comment by eusonlito** [comment]
Braintree developers are working to integrate my PSR-4 fork (updated to last release) into the main project. https://github.com/braintree/braintree_php/pull/99 :)

**Comment by LukeXF** [comment]
Thanks, I look forward to seeing it

**Comment by GiantCowFilms** [comment]
@eusonlito Hurrah! :)

**Comment by ryantology** [comment]
Thank you @eusonlito It's quite embarrassing to see old school namespace pollution all over the place. 

It doesn't look like @crookedneighbor works for braintree (or hasn't made commits to this repo before). Would be nice to get a response from @bryanagee on if there is an ETA for this change. This is a significant improvement.

**Comment by bryanagee** [comment]
I absolutely agree, but I don't work for braintree either, so I couldn't tell you =)

**Comment by ryantology** [comment]
Oh sorry.

It looks like @matthewpatterson (who does work for braintree?) already started a discussion on #79 regarding this. Would love to see some updates / status.

@eusonlito unfortunately your version renamed the composer.json package name so it likely won't be merged as a PR.

**Comment by eusonlito** [comment]
Ok @ryantology, I can change the composer.json to your package.

**Comment by eusonlito** [comment]
Done, was added to PR.

**Comment by matthewpatterson** [comment]
Hey all, I am a developer at Braintree. We are working to integrate @eusonlito's work to namespace all of the classes in this library and enable PSR-4 autoloading. We are getting very close to being able to release it. @crookedneighbor (who does indeed work for Braintree) is more familiar with the release schedule than I am, so I think on Monday he'll be able to give you a better idea of when this change will be released.

**Comment by ryantology** [comment]
Amazing, thanks for the update! I have started testing with @eusonlito
version and so far it is working OK. Excited to see a psr version of this
library.

**Comment by crookedneighbor** [comment]
We've added support for PSR-4 namespacing in [version 3.6.0](https://github.com/braintree/braintree_php/releases/tag/3.6.0). Thanks to @eusonlito  for starting the hard work of converting it over!

Version 3.6.0 is backwards compatible with the old class names syntax, so either can be used.

**Comment by GiantCowFilms** [comment]
@crookedneighbor Thank you! :D Going to update my apps today. Good to see your all working to make your API more usable.
