### ISSUE TITLE
Subscription Discount Error

### ISSUE THREAD

**Issue by ahmetemir** [braintree/braintree_php#96]
I want to apply discount to subscription but it returns with error (code:91921) : Invalid request format.

This is my subscription array passed to **Braintree_Subscription::create** 
```
array(5) {
  ["paymentMethodToken"]=>
  string(6) "xxxxx"
  ["planId"]=>
  string(4) "f776"
  ["price"]=>
  float(1245)
  ["merchantAccountId"]=>
  string(11) "xxxxx"
  ["discounts"]=>
  array(1) {
    ["add"]=>
    array(5) {
      ["inheritedFromId"]=>
      string(4) "7gpb"
      ["quantity"]=>
      int(1)
      ["neverExpires"]=>
      bool(false)
      ["numberOfBillingCycles"]=>
      int(1)
      ["amount"]=>
      string(7) "13.20"
    }
  }
}
```
Local library successfully parse and send request (no invalid key error) but braintree says its format is invalid.Error code says it's about add-ons or discount but no details.Any idea?

**Comment by ikolubr** [comment]
Hi there. Did you find a solution for this problem? I'm at the same boat here!

**Comment by louismrose** [comment]
I also ran into this today. The issue I faced -- and possibly the same as OP -- was that the `["discounts"]["add"]` parameter must be an array of arrays.

In other words, this will **not** work:

```php
[
  "paymentMethodToken" => "xxxxx",
  "planId" => "f776",
  "price" => 1245,
  "merchantAccountId" => "xxxxx"
  "discounts" => [
    "add" => [
      "inheritedFromId" => "7gpb",
      "quantity" => 1,
      "neverExpires" => false,
      "numberOfBillingCycles" => 1,
      "amount" => "13.20"
    ]
  ]
]
```

But this will:

```php
[
  "paymentMethodToken" => "xxxxx",
  "planId" => "f776",
  "price" => 1245,
  "merchantAccountId" => "xxxxx"
  "discounts" => [
    "add" => [
      [ // NB: each element of add must be an array
        "inheritedFromId" => "7gpb",
        "quantity" => 1,
        "neverExpires" => false,
        "numberOfBillingCycles" => 1,
        "amount" => "13.20"
      ]
    ]
  ]
]
```

The same array of array structure must be used with the `addOns` parameter.

**Comment by crookedneighbor** [comment]
I've submitted your feedback to our docs team, we'll look into adding a discounts example to go with the addOns one.

**Comment by louismrose** [comment]
Thanks @crookedneighbor! It'd be brilliant if the SDK could do some type checking here too -- maybe throwing an error before sending the request if the `add`, `update` or `remove` fields are not arrays. I spent a good couple of hours on this, and even raised a support request!
