### ISSUE TITLE
addBillingAddressToPaymentMethod duplicates addresses

### ISSUE THREAD

**Issue by ericcholis** [braintree/braintree_php#97]
I've noticed that specifying `addBillingAddressToPaymentMethod` along with a billing address id via `Braintree_Transaction::sale()` is duplicating the address in an existing customer's vault.

Here's a sample request:

```php
$result = Braintree_Transaction::sale([
    "paymentMethodNonce" => "fake-valid-nonce",
    "amount" => 96.68,
    "orderId" => "TEST123",
    "options" => [
        "submitForSettlement" => false,
        "storeInVault" => true,
        "addBillingAddressToPaymentMethod" => true
    ],
    "channel" => "mysite.com",
    "customerId" => "CUSTOMERID",
    "shippingAddressId" => "ADDRESSID",
    "billingAddressId" => "ADDRESSID"
]);
```

The billing address is correctly applied to the payment method in the vault. However it's done so with a new ID rather than re-use the one specified in the `billingAddressId` parameter.

Replace ADDRESSID with an address that already exists for your customer. Perhaps I'm doing something incorrectly.

I've experienced this when using versions 2.40 and 3.4

**Comment by raymondberg** [comment]
Hi @ericcholis. We haven't been able to reproduce this on our side, and this is not a great venue for troubleshooting individual issues. I would recommend opening a ticket with [Braintree support](https://support.braintreepayments.com) so you can share more details about your environment and possible information about your account setup. I'm going to close this issue out now, but if you discover through support that this is a code issue feel free to reopen.
