### ISSUE TITLE
Is Braintree_CreditCard really deprecated  ?

### ISSUE THREAD

**Issue by rained23** [braintree/braintree_php#98]
Hi,

I am wondering in the documentation, Braintree_CreditCard was stated as deprecated, but when
I getting Customer->paymentMethods() it returns Braintree_CreditCard object, and somehow creditCards() is duplicate of paymentMethods, should paymentMethods return Braintree_PaymentMethod object instead ?

**Comment by raymondberg** [comment]
Thanks for your comment, @rained23. The deprecation is best understood as "you shouldn't be creating/finding credit cards using this method" and not "this data type is not used", but I can appreciate the confusion. If you have any other questions on the docs be sure to [contact our support team](https://support.braintreepayments.com) or leave feedback at the bottom of the docs pages. We're always working to make it clear, while still providing the documentation for older integrations.

Per the [PaymentMethod documentation](https://developers.braintreepayments.com/ios+php/reference/response/payment-method) multiple object types may return out of payment method inquiries. Depending on which object it is there might be specific attributes that are not common to another type.
